tpie::disjoint_sets< value_t > Class Template Reference
tpie::disjoint_sets< value_t > Class Template Reference
Internal memory union find implementation.
#include <tpie/disjoint_sets.h>
Inherits tpie::linear_memory_base< disjoint_sets< size_type > >.
Public Member Functions
disjoint_sets (size_type n=0, value_t u=default_unused< value_t >::v(), tpie::memory_bucket_ref b=tpie::memory_bucket_ref())
Construct a empty collection of disjoint sets.
disjoint_sets (tpie::memory_bucket_ref b)
void make_set (value_t element)
Make a singleton set.
bool is_set (value_t element)
Check if a given element is a member of any set.
value_t link (value_t a, value_t b)
Union two sets given by their representatives.
value_t find_set (value_t t)
Find the representative of the set contaning a given element.
value_t union_set (value_t a, value_t b)
Union the set containing a with the set containing b.
size_type count_sets ()
Return the number of sets.
void clear ()
Clears all sets contained in the datastructure.
void resize (size_t size)
Changes the size of the datastructure.
Static Public Member Functions
static double memory_coefficient ()
Return the memory coefficient of the structure.
static double memory_overhead ()
Return the memory overhead of the structure.
static constexpr memory_size_type memory_usage (memory_size_type size) noexcept
Return the number of bytes required to create a data structure supporting a given number of elements.
static constexpr linear_memory_usage memory_usage () noexcept
static constexpr memory_size_type memory_fits (memory_size_type memory) noexcept
Return the maximum number of elements that can be contained in in the structure when it is allowed to fill a given number of bytes.
Detailed Description
template<typename value_t = size_type>
class tpie::disjoint_sets< value_t >
Internal memory union find implementation.
The key space is the first n integers (from 0 to n-1). n is given in the constructor.
Template Parameters
value_t The type of values stored (must be an integer type).
Definition at line 43 of file disjoint_sets.h.
Constructor & Destructor Documentation
disjoint_sets()
template<typename value_t = size_type> tpie::disjoint_sets< value_t >::disjoint_sets (size_type n = 0, value_t u = default_unused<value_t>::v(), tpie::memory_bucket_ref b = tpie::memory_bucket_ref()) inline
Construct a empty collection of disjoint sets.
Parameters
n The maximal number of sets to support
u A value you guarentee not to use.
Definition at line 71 of file disjoint_sets.h.
         : m_elements(n, u, b), m_unused(u), m_size(0) {}
Referenced by tpie::disjoint_sets< value_t >::memory_overhead().
Member Function Documentation
clear()
template<typename value_t = size_type> void tpie::disjoint_sets< value_t >::clear () inline
Clears all sets contained in the datastructure.
Definition at line 164 of file disjoint_sets.h.
                  {
         std::fill(m_elements.begin(), m_elements.end(), m_unused);
         m_size = 0;
     }
References tpie::array< T, Allocator >::begin(), and tpie::array< T, Allocator >::end().
count_sets()
template<typename value_t = size_type> size_type tpie::disjoint_sets< value_t >::count_sets () inline
Return the number of sets.
Definition at line 157 of file disjoint_sets.h.
{
         return m_size;
     }
find_set()
template<typename value_t = size_type> value_t tpie::disjoint_sets< value_t >::find_set (value_t t) inline
Find the representative of the set contaning a given element.
Parameters
t The element of which to find the set representative
Returns
The representative.
Definition at line 115 of file disjoint_sets.h.
{
         // If t sits in depth d, we halve the depth of d/2 nodes in the tree,
         // including t.
         while (true) {
             // Set t to point to its grandparent.
             value_t x = m_elements[m_elements[t]];
             if (x == t) return t;
             m_elements[t] = x;
             t = x;
         }
         // The textbook implementation below is faster for some adversarial
         // inputs, but is cache inefficient on ordinary input.
         //value_t r = m_elements[t];
         //if (r == t)
         //  return r;
         //while (r != m_elements[r])
         //  r = m_elements[r];
         //while (t != r) {
         //  value_t next = m_elements[t];
         //  m_elements[t] = r;
         //  t = next;
         //}
         //return r;
     }
Referenced by tpie::disjoint_sets< value_t >::union_set().
is_set()
template<typename value_t = size_type> bool tpie::disjoint_sets< value_t >::is_set (value_t element) inline
Check if a given element is a member of any set.
This is the same as saying if make_set has ever been called with the given key
Parameters
element The key to check
Definition at line 92 of file disjoint_sets.h.
 {return m_elements[element] != m_unused;}
link()
template<typename value_t = size_type> value_t tpie::disjoint_sets< value_t >::link (value_t a, value_t b) inline
Union two sets given by their representatives.
Parameters
a The representative of one set
b The representative of the other set
Returns
The representative of the combined set
Definition at line 101 of file disjoint_sets.h.
{
         if (a == b) return a;
         --m_size;
         m_elements[b] = a;
         return a;
     }
Referenced by tpie::disjoint_sets< value_t >::union_set().
make_set()
template<typename value_t = size_type> void tpie::disjoint_sets< value_t >::make_set (value_t element) inline
Make a singleton set.
Parameters
element The key of the singleton set to create
Definition at line 83 of file disjoint_sets.h.
 {m_elements[element] = element; ++m_size;}
memory_coefficient()
template<typename value_t = size_type> static double tpie::disjoint_sets< value_t >::memory_coefficient () inline static
Return the memory coefficient of the structure.
Allocating a structure with n elements will use at most \(\lfloor \mathrm{memory\_coefficient} \cdot n + \mathrm{memory\_overhead} \rfloor \) bytes. This does not include memory overhead incurred if the structure is allocated using new.
Returns
The memory coefficient of the structure.
Definition at line 53 of file disjoint_sets.h.
{
         return array<value_t>::memory_coefficient();
     }
References tpie::array< T, Allocator >::memory_coefficient().
memory_fits()
static constexpr memory_size_type tpie::linear_memory_base< disjoint_sets< size_type > >::memory_fits (memory_size_type memory) inline static constexpr noexcept inherited
Return the maximum number of elements that can be contained in in the structure when it is allowed to fill a given number of bytes.
Parameters
memory The number of bytes the structure is allowed to occupy
Returns
The number of elements that will fit in the structure
Definition at line 118 of file util.h.
{
         return static_cast<memory_size_type>(
             floor((memory - child_t::memory_overhead()) / child_t::memory_coefficient()));
     }
memory_overhead()
template<typename value_t = size_type> static double tpie::disjoint_sets< value_t >::memory_overhead () inline static
Return the memory overhead of the structure.
See also
memory_coefficient()
Returns
The memory overhead.
Definition at line 61 of file disjoint_sets.h.
{
         return array<value_t>::memory_overhead() + sizeof(disjoint_sets) - sizeof(array<value_t>);
     }
References tpie::disjoint_sets< value_t >::disjoint_sets(), and tpie::array< T, Allocator >::memory_overhead().
memory_usage()
static constexpr memory_size_type tpie::linear_memory_base< disjoint_sets< size_type > >::memory_usage (memory_size_type size) inline static constexpr noexcept inherited
Return the number of bytes required to create a data structure supporting a given number of elements.
Parameters
size The number of elements to support
Returns
The amount of memory required in bytes
Definition at line 106 of file util.h.
{
         return static_cast<memory_size_type>(
             floor(static_cast<double>(size) * child_t::memory_coefficient() + child_t::memory_overhead()));
     }
resize()
template<typename value_t = size_type> void tpie::disjoint_sets< value_t >::resize (size_t size) inline
Changes the size of the datastructure.
All elements are lost.
Definition at line 173 of file disjoint_sets.h.
{
         m_elements.resize(size, m_unused);
         m_size = 0;
     }
References tpie::array< T, Allocator >::resize().
union_set()
template<typename value_t = size_type> value_t tpie::disjoint_sets< value_t >::union_set (value_t a, value_t b) inline
Union the set containing a with the set containing b.
Parameters
a An element in one set
b An element in another set (possible)
Returns
The representative of the unioned set
Definition at line 150 of file disjoint_sets.h.
{
         return link(find_set(a), find_set(b));
     }
References tpie::disjoint_sets< value_t >::find_set(), and tpie::disjoint_sets< value_t >::link().
The documentation for this class was generated from the following file:
disjoint_sets.h