tpie::pipelining::virtual_chunk_pull_begin< Output > Class Template Reference
tpie::pipelining::virtual_chunk_pull_begin< Output > Class Template Reference
Virtual chunk that has no output (that is, virtual consumer).
#include <tpie/pipelining/virtual.h>
Public Member Functions
virtual_chunk_pull_begin ()
Constructor that leaves the virtual chunk unassigned.
template<typename fact_t >
virtual_chunk_pull_begin (pullpipe_begin< fact_t > &&pipe, virtual_container *ctr=nullptr)
Constructor that recursively constructs a node and takes ownership of it.
template<typename fact_t >
virtual_chunk_pull_begin & operator= (pullpipe_begin< fact_t > &&pipe)
Construct a node and assign it to this virtual chunk.
virtual_chunk_base operator| (virtual_chunk_pull_end< Output > dest)
Connect this virtual chunk to another chunk.
template<typename NextOutput >
virtual_chunk_pull_begin< NextOutput > operator| (virtual_chunk_pull< Output, NextOutput > dest)
Connect this virtual chunk to another chunk.
operator bool () const noexcept
Test if it is not an empty chunk.
Friends
class bits::access
Detailed Description
template<typename Output>
class tpie::pipelining::virtual_chunk_pull_begin< Output >
Virtual chunk that has no output (that is, virtual consumer).
Definition at line 68 of file virtual.h.
Constructor & Destructor Documentation
virtual_chunk_pull_begin() [1/2]
template<typename Output > tpie::pipelining::virtual_chunk_pull_begin< Output >::virtual_chunk_pull_begin () inline
Constructor that leaves the virtual chunk unassigned.
Definition at line 919 of file virtual.h.
         : m_output(nullptr)
     {}
virtual_chunk_pull_begin() [2/2]
template<typename Output > template<typename fact_t > tpie::pipelining::virtual_chunk_pull_begin< Output >::virtual_chunk_pull_begin (pullpipe_begin< fact_t > && pipe, virtual_container * ctr = nullptr) inline
Constructor that recursively constructs a node and takes ownership of it.
Definition at line 928 of file virtual.h.
{
         *this = std::forward<pullpipe_begin<fact_t>>(pipe);
         set_container(ctr);
     }
Member Function Documentation
operator bool()
template<typename Output > tpie::pipelining::virtual_chunk_pull_begin< Output >::operator bool () const inline explicit noexcept
Test if it is not an empty chunk.
Definition at line 984 of file virtual.h.
{
         return m_output != nullptr;
     }
operator=()
template<typename Output > template<typename fact_t > virtual_chunk_pull_begin& tpie::pipelining::virtual_chunk_pull_begin< Output >::operator= (pullpipe_begin< fact_t > && pipe) inline
Construct a node and assign it to this virtual chunk.
Definition at line 937 of file virtual.h.
{
         if (this->m_node) {
             log_error() << "Virtual chunk assigned twice" << std::endl;
             throw tpie::exception("Virtual chunk assigned twice");
         }
         typedef typename fact_t::constructed_type constructed_type;
         m_output = new bits::virtpullsrc_impl<constructed_type, Output>(pipe.factory.construct());
         this->m_node = bits::virt_node::take_own(m_output);
         this->m_nodeMap = m_output->get_node_map();
         return *this;
     }
References tpie::log_error(), and tpie::pipelining::bits::virt_node::take_own().
operator|() [1/2]
template<typename Output > template<typename NextOutput > virtual_chunk_pull_begin<NextOutput> tpie::pipelining::virtual_chunk_pull_begin< Output >::operator| (virtual_chunk_pull< Output, NextOutput > dest) inline
Connect this virtual chunk to another chunk.
Definition at line 970 of file virtual.h.
{
         if (empty()) throw virtual_chunk_missing_begin();
         if (dest.empty()) {
             return *bits::assert_types_equal_and_return<Output, NextOutput, virtual_chunk_pull_begin<NextOutput> *>
                 ::go(this);
         }
         acc::get_input(dest)->set_source(get_output());
         return acc::construct<virtual_chunk_pull_begin<NextOutput>>(*this, dest);
     }
operator|() [2/2]
template<typename Output > virtual_chunk_base tpie::pipelining::virtual_chunk_pull_begin< Output >::operator| (virtual_chunk_pull_end< Output > dest) inline
Connect this virtual chunk to another chunk.
Definition at line 955 of file virtual.h.
{
         if (empty()) throw virtual_chunk_missing_begin();
         if (dest.empty()) throw virtual_chunk_missing_end();
         acc::get_input(dest)->set_source(get_output());
         return acc::construct<virtual_chunk_base>(
             this->m_nodeMap,
             bits::virt_node::combine(get_node(), dest.get_node()));
     }
References tpie::pipelining::bits::virt_node::combine().
The documentation for this class was generated from the following file:
pipelining/virtual.h