tpie::progress_indicator_base Class Reference
tpie::progress_indicator_base Class Reference abstract
The base class for indicating the progress of some task.
#include <tpie/progress_indicator_base.h>
Inherited by tpie::pipelining::bits::proxy_progress_indicator, tpie::progress_indicator_null, tpie::progress_indicator_subindicator, and tpie::progress_indicator_terminal.
Public Member Functions
progress_indicator_base (stream_size_type range)
Initializes the indicator.
virtual ~progress_indicator_base ()
Destructor.
progress_indicator_base (progress_indicator_base &&o)
progress_indicator_base & operator= (progress_indicator_base &&o)
progress_indicator_base ()=delete
Deleted default constructor.
progress_indicator_base (const progress_indicator_base &)=delete
Deleted copy constructor.
progress_indicator_base & operator= (const progress_indicator_base &)=delete
Deleted assignment operator.
void step (stream_size_type step=1)
Record an increment to the indicator and advance the indicator.
void raw_step (stream_size_type step)
Internal method used in fractional progress.
virtual void init (stream_size_type range=0)
Initialize progress indicator.
virtual void done ()
Advance the indicator to the end.
virtual void set_range (stream_size_type range)
Set the upper bound of the counting range.
virtual void refresh ()=0
Display the indicator.
stream_size_type get_current ()
Get the current value of the step counter.
stream_size_type get_range ()
Get the maximum value of the current range.
execution_time_predictor * get_time_predictor ()
void set_time_predictor (execution_time_predictor *p)
std::string estimated_remaining_time ()
virtual void push_breadcrumb (const char *, description_importance)
virtual void pop_breadcrumb ()
Protected Attributes
stream_size_type m_range
The upper bound of the counting range.
stream_size_type m_current
The current progress count [m_minRange...m_maxRange].
Detailed Description
The base class for indicating the progress of some task.
At times, especially when processing large data sets, the user might want the program to provide information about how much progress has been made. TPIE provides a class hierarchy with an abstract base class progress_indicator_base for realizing such indicators. TPIE offers terminal-based indicators, such as progress_indicator_arrow that shows an extending arrow or progress_indicator_spin that shows a spinning "wheel". To allow for other types of indicators such as graphics-based indicators for (interfaces to) indicators provided by other APIs, the terminal-based indicators inherit from progress_indicator_terminal which in turn inherits from progress_indicator_base. To include other types of non-terminal-based indicators, the user thus should subclass progress_indicator_base. All indicators are based upon the following concept: The indicator is given a range [minRange , maxRange ] and a parameter stepValue/ For each update to the indicator and starting at minRange , the progress status will be advanced by stepValue units.
Definition at line 62 of file progress_indicator_base.h.
Constructor & Destructor Documentation
progress_indicator_base() [1/3]
tpie::progress_indicator_base::progress_indicator_base (stream_size_type range)
Initializes the indicator.
Parameters
range The upper bound of the counting range.
~progress_indicator_base()
virtual tpie::progress_indicator_base::~progress_indicator_base () virtual
Destructor.
progress_indicator_base() [2/3]
tpie::progress_indicator_base::progress_indicator_base () delete
Deleted default constructor.
progress_indicator_base() [3/3]
tpie::progress_indicator_base::progress_indicator_base (const progress_indicator_base &) delete
Deleted copy constructor.
Member Function Documentation
done()
virtual void tpie::progress_indicator_base::done () inline virtual
Advance the indicator to the end.
Reimplemented in tpie::progress_indicator_terminal, tpie::fractional_subindicator, tpie::progress_indicator_subindicator, and tpie::progress_indicator_null.
Definition at line 130 of file progress_indicator_base.h.
 {}
Referenced by tpie::merge_sorter< T, UseProgress, pred_t, store_t >::calc(), and tpie::parallel_sort().
get_current()
stream_size_type tpie::progress_indicator_base::get_current () inline
Get the current value of the step counter.
Definition at line 152 of file progress_indicator_base.h.
 { return m_current; }
get_range()
stream_size_type tpie::progress_indicator_base::get_range () inline
Get the maximum value of the current range.
Definition at line 157 of file progress_indicator_base.h.
 { return m_range; }
init()
virtual void tpie::progress_indicator_base::init (stream_size_type range = 0) inline virtual
Initialize progress indicator.
Parameters
range The number of times step() is going to be called.
Reimplemented in tpie::fractional_subindicator, tpie::progress_indicator_subindicator, and tpie::progress_indicator_null.
Definition at line 121 of file progress_indicator_base.h.
{
         if (range != 0) set_range(range);
         m_current = 0;
         call_refresh();
     }
Referenced by tpie::merge_sorter< T, UseProgress, pred_t, store_t >::calc(), and tpie::parallel_sort().
operator=()
progress_indicator_base& tpie::progress_indicator_base::operator= (const progress_indicator_base &) delete
Deleted assignment operator.
raw_step()
void tpie::progress_indicator_base::raw_step (stream_size_type step) inline
Internal method used in fractional progress.
In a hierarchy of fractional progress subindicators, only the lowest level of indicators should determine how many steps should pass until the next call to refresh(). When this happens, the subindicator calls raw_step() on its parent indicator rather than step(), which will short-circuit the logic and call the virtual method refresh() directly. You should probably not use this method; use step() instead.
Definition at line 111 of file progress_indicator_base.h.
{
         m_current += step;
         // Don't call call_refresh(); call refresh() directly instead.
         refresh();
     }
refresh()
virtual void tpie::progress_indicator_base::refresh () pure virtual
Display the indicator.
Implemented in tpie::pipelining::bits::proxy_progress_indicator, tpie::progress_indicator_terminal, tpie::progress_indicator_spin, tpie::progress_indicator_arrow, tpie::progress_indicator_null, and tpie::progress_indicator_subindicator.
set_range()
virtual void tpie::progress_indicator_base::set_range (stream_size_type range) inline virtual
Set the upper bound of the counting range.
This method also implies a reset of the counter. In order to be able to set the uper bound independent of setting the lower bound, no range checking is done.
Parameters
range The new upper bound.
Reimplemented in tpie::progress_indicator_null.
Definition at line 140 of file progress_indicator_base.h.
{
         m_range = range;
     }
step()
void tpie::progress_indicator_base::step (stream_size_type step = 1) inline
Record an increment to the indicator and advance the indicator.
Definition at line 91 of file progress_indicator_base.h.
{
         m_current += step;
         if (step >= m_remainingSteps) {
             call_refresh();
         } else {
             m_remainingSteps -= step;
         }
     }
Referenced by tpie::merge_sorter< T, UseProgress, pred_t, store_t >::calc(), and tpie::ami::Internal_Sorter_Obj< T, Compare >::sort().
Member Data Documentation
m_current
stream_size_type tpie::progress_indicator_base::m_current protected
The current progress count [m_minRange...m_maxRange].
Definition at line 174 of file progress_indicator_base.h.
Referenced by tpie::progress_indicator_terminal::display_percentage(), tpie::progress_indicator_terminal::done(), tpie::progress_indicator_arrow::refresh(), tpie::progress_indicator_spin::refresh(), and tpie::progress_indicator_arrow::reset().
m_range
stream_size_type tpie::progress_indicator_base::m_range protected
The upper bound of the counting range.
Definition at line 171 of file progress_indicator_base.h.
Referenced by tpie::progress_indicator_terminal::display_percentage(), tpie::progress_indicator_terminal::done(), and tpie::progress_indicator_arrow::refresh().
The documentation for this class was generated from the following file:
progress_indicator_base.h