tpie::pipelining::bits::pipe_nonterm_base< child_t > Class Template Reference
tpie::pipelining::bits::pipe_nonterm_base< child_t > Class Template Reference
Inherits tpie::pipelining::bits::pipe_base< child_t >.
Classes
class constructed
Public Types
template<typename dest_t >
using constructed_type = typename constructed< dest_t >::type
Public Member Functions
pipe_nonterm_base (const pipe_nonterm_base &)=delete
pipe_nonterm_base (pipe_nonterm_base &&)=default
pipe_nonterm_base & operator= (const pipe_nonterm_base &)=delete
pipe_nonterm_base & operator= (pipe_nonterm_base &&)=default
template<typename dest_t >
constructed_type< dest_t > construct (const dest_t &dest)
child_t memory (double amount)
Set memory fraction for this node in the pipeline phase.
double memory () const
Get memory fraction for this node in the pipeline phase.
child_t name (const std::string &n, priority_type p=PRIORITY_USER)
Set name for this node.
child_t phase_name (const std::string &n, priority_type p=PRIORITY_USER)
Set name for this phase.
child_t add_to_set (node_set s)
Get a refenerce to this node.
child_t add_dependencies (node_set s)
Add a depencency to a referenced node.
child_t add_forwarding_dependencies (node_set s)
Add a forwarding dependency to a referenced node.
child_t breadcrumb (const std::string &n)
Set a prefix for the name of this node.
child_t forward_any (const std::string &key, any_noncopyable value)
template<typename T >
child_t forward (const std::string &key, T value)
Protected Member Functions
child_t & self ()
const child_t & self () const
Detailed Description
template<typename child_t>
class tpie::pipelining::bits::pipe_nonterm_base< child_t >
Definition at line 186 of file pipe_base.h.
Member Function Documentation
add_dependencies()
template<typename child_t > child_t tpie::pipelining::bits::pipe_base< child_t >::add_dependencies (node_set s) inline inherited
Add a depencency to a referenced node.
See also
factory_base::ref
Definition at line 125 of file pipe_base.h.
{
         self().factory.add_dependencies(s);
         return std::move(self());
     }
add_forwarding_dependencies()
template<typename child_t > child_t tpie::pipelining::bits::pipe_base< child_t >::add_forwarding_dependencies (node_set s) inline inherited
Add a forwarding dependency to a referenced node.
See also
factory_base::ref
Definition at line 135 of file pipe_base.h.
{
         self().factory.add_forwarding_dependencies(s);
         return std::move(self());
     }
add_to_set()
template<typename child_t > child_t tpie::pipelining::bits::pipe_base< child_t >::add_to_set (node_set s) inline inherited
Get a refenerce to this node.
This reference can be used to call add_dependency on another node
See also
factory_base::ref
Definition at line 115 of file pipe_base.h.
{
         self().factory.add_to_set(s);
         return std::move(self());
     }
breadcrumb()
template<typename child_t > child_t tpie::pipelining::bits::pipe_base< child_t >::breadcrumb (const std::string & n) inline inherited
Set a prefix for the name of this node.
The name is used in the GraphViz plot generated by pipeline::plot.
See also
factory_base::push_breadcrumb
Definition at line 147 of file pipe_base.h.
{
         self().factory.push_breadcrumb(n);
         return std::move(self());
     }
memory() [1/2]
template<typename child_t > double tpie::pipelining::bits::pipe_base< child_t >::memory () const inline inherited
Get memory fraction for this node in the pipeline phase.
See also
memory(double)
factory_base::memory()
Definition at line 74 of file pipe_base.h.
{
         return self().factory.memory();
     }
memory() [2/2]
template<typename child_t > child_t tpie::pipelining::bits::pipe_base< child_t >::memory (double amount) inline inherited
Set memory fraction for this node in the pipeline phase.
In the absence of minimum and maximum memory requirements set by node implementations, the memory assigned to the node will be proportional to the amount parameter which sets the memory priority of this node in relation to the rest of the phase.
See also
factory_base::memory(double)
Definition at line 63 of file pipe_base.h.
{
         self().factory.memory(amount);
         return std::move(self());
     }
name()
template<typename child_t > child_t tpie::pipelining::bits::pipe_base< child_t >::name (const std::string & n, priority_type p = PRIORITY_USER) inline inherited
Set name for this node.
The name is used in the GraphViz plot generated by pipeline::plot.
The name priority given in the second argument should indicate how important this node is for the current phase, and is used in naming the progress indicator for this phase. The node with the highest priority name gets to name the entire phase.
See also
factory_base::name
Definition at line 90 of file pipe_base.h.
{
         self().factory.name(n, p);
         return std::move(self());
     }
Referenced by tpie::pipelining::serialization_sort(), tpie::pipelining::sort(), and tpie::pipelining::store_sort().
phase_name()
template<typename child_t > child_t tpie::pipelining::bits::pipe_base< child_t >::phase_name (const std::string & n, priority_type p = PRIORITY_USER) inline inherited
Set name for this phase.
The maximal priority phase name given for a phase wins.
See also
factory_base::phase_name
Definition at line 102 of file pipe_base.h.
{
         self().factory.phase_name(n, p);
         return std::move(self());
     }
The documentation for this class was generated from the following file:
pipelining/pipe_base.h