tpie::fractional_progress Class Reference
tpie::fractional_progress Class Reference
Fractional progress reporter.
#include <tpie/fractional_progress.h>
Public Member Functions
fractional_progress (progress_indicator_base *pi)
void done ()
Advance the indicator to the end.
void init (stream_size_type range=0)
Initialize progress indicator.
unique_id_type & id ()
Return this progress indicator's unique id.
void push_breadcrumb (const char *crumb, description_importance importance)
void pop_breadcrumb ()
Friends
class fractional_subindicator
Detailed Description
Fractional progress reporter.
Definition at line 108 of file fractional_progress.h.
Member Function Documentation
done()
void tpie::fractional_progress::done ()
Advance the indicator to the end.
Referenced by tpie::ami::Internal_Sorter_Obj< T, Compare >::sort().
id()
unique_id_type& tpie::fractional_progress::id ()
Return this progress indicator's unique id.
Referenced by tpie::ami::Internal_Sorter_Obj< T, Compare >::sort().
init()
void tpie::fractional_progress::init (stream_size_type range = 0)
Initialize progress indicator.
Parameters
range The number of times step() is going to be called.
Referenced by tpie::ami::Internal_Sorter_Obj< T, Compare >::sort().
The documentation for this class was generated from the following file:
fractional_progress.h