tpie::compressor_buffer Class Reference
tpie::compressor_buffer Class Reference
A buffer for elements belonging to a specific stream block.
#include <tpie/compressed/buffer.h>
Public Member Functions
compressor_buffer (memory_size_type capacity)
compressor_buffer_state::type get_state () const
void set_state (compressor_buffer_state::type to)
void transition_state (compressor_buffer_state::type from, compressor_buffer_state::type to)
bool is_busy ()
char * get ()
Get pointer to buffer storage.
const char * get () const
Get pointer to buffer storage.
memory_size_type size () const
Get number of bytes used to store items.
memory_size_type capacity () const
Get maximal byte size of buffer.
void set_size (memory_size_type size)
Set number of bytes used to store items.
void set_capacity (memory_size_type capacity)
Resize internal buffer, clearing all elements.
void reset ()
Return buffer to a newly constructed state.
memory_size_type get_block_size ()
stream_size_type get_read_offset ()
void set_block_size (memory_size_type s)
void set_read_offset (stream_size_type s)
Detailed Description
A buffer for elements belonging to a specific stream block.
Definition at line 85 of file buffer.h.
Member Function Documentation
capacity()
memory_size_type tpie::compressor_buffer::capacity () const inline
Get maximal byte size of buffer.
Definition at line 159 of file buffer.h.
{
         return m_storage.size();
     }
References tpie::array< T, Allocator >::size().
Referenced by set_capacity().
get() [1/2]
char* tpie::compressor_buffer::get () inline
Get pointer to buffer storage.
Definition at line 138 of file buffer.h.
                  {
         return m_storage.get();
     }
References tpie::array< T, Allocator >::get().
get() [2/2]
const char* tpie::compressor_buffer::get () const inline
Get pointer to buffer storage.
Definition at line 145 of file buffer.h.
{
         return m_storage.get();
     }
References tpie::array< T, Allocator >::get().
reset()
void tpie::compressor_buffer::reset () inline
Return buffer to a newly constructed state.
Definition at line 181 of file buffer.h.
                  {
         m_state = compressor_buffer_state::dirty;
         m_size = 0;
         m_readOffset = 1111111111111111111ull;
         m_blockSize = std::numeric_limits<memory_size_type>::max();
     }
References tpie::compressor_buffer_state::dirty.
set_capacity()
void tpie::compressor_buffer::set_capacity (memory_size_type capacity) inline
Resize internal buffer, clearing all elements.
Definition at line 173 of file buffer.h.
{
         m_storage.resize(capacity);
         m_size = 0;
     }
References capacity(), and tpie::array< T, Allocator >::resize().
set_size()
void tpie::compressor_buffer::set_size (memory_size_type size) inline
Set number of bytes used to store items.
Definition at line 166 of file buffer.h.
{
         m_size = size;
     }
References size().
size()
memory_size_type tpie::compressor_buffer::size () const inline
Get number of bytes used to store items.
Definition at line 152 of file buffer.h.
{
         return m_size;
     }
Referenced by set_size().
The documentation for this class was generated from the following file:
compressed/buffer.h