tpie::pipelining::virtual_chunk_pull< Input, Output > Class Template Reference
tpie::pipelining::virtual_chunk_pull< Input, Output > Class Template Reference
Virtual chunk that has input and output.
#include <tpie/pipelining/virtual.h>
Public Member Functions
virtual_chunk_pull ()
Constructor that leaves the virtual chunk unassigned.
template<typename fact_t >
virtual_chunk_pull (pullpipe_middle< fact_t > &&pipe, virtual_container *ctr=nullptr)
Constructor that recursively constructs a node and takes ownership of it.
virtual_chunk_pull (const virtual_chunk_pull_end< Input > &left, const virtual_chunk_pull_begin< Output > &right)
Construct a virtual chunk pull from an end and a begin chunk.
template<typename fact_t >
virtual_chunk_pull & operator= (pullpipe_middle< fact_t > &&pipe)
Construct a node and assign it to this virtual chunk.
template<typename NextOutput >
virtual_chunk_pull< Input, NextOutput > operator| (virtual_chunk_pull< Output, NextOutput > dest)
Connect this virtual chunk to another chunk.
virtual_chunk_pull_end< Input > operator| (virtual_chunk_pull_end< Output > dest)
Connect this virtual chunk to another chunk.
operator bool () const noexcept
Test if it is not an empty chunk.
Friends
class bits::access
Detailed Description
template<typename Input, typename Output = Input>
class tpie::pipelining::virtual_chunk_pull< Input, Output >
Virtual chunk that has input and output.
Definition at line 64 of file virtual.h.
Constructor & Destructor Documentation
virtual_chunk_pull() [1/3]
template<typename Input , typename Output = Input> tpie::pipelining::virtual_chunk_pull< Input, Output >::virtual_chunk_pull () inline
Constructor that leaves the virtual chunk unassigned.
Definition at line 806 of file virtual.h.
         : m_input(nullptr)
         , m_output(nullptr)
     {}
virtual_chunk_pull() [2/3]
template<typename Input , typename Output = Input> template<typename fact_t > tpie::pipelining::virtual_chunk_pull< Input, Output >::virtual_chunk_pull (pullpipe_middle< fact_t > && pipe, virtual_container * ctr = nullptr) inline
Constructor that recursively constructs a node and takes ownership of it.
Definition at line 816 of file virtual.h.
{
         *this = std::forward<pullpipe_middle<fact_t>>(pipe);
         set_container(ctr);
     }
virtual_chunk_pull() [3/3]
template<typename Input , typename Output = Input> tpie::pipelining::virtual_chunk_pull< Input, Output >::virtual_chunk_pull (const virtual_chunk_pull_end< Input > & left, const virtual_chunk_pull_begin< Output > & right) inline
Construct a virtual chunk pull from an end and a begin chunk.
Items pushed into the virtual chunk are pushed into the left end chunk Items push out of the right begin chenk are pushed out of the virtual chunk
Definition at line 827 of file virtual.h.
         : virtual_chunk_base(left.get_node_map(), bits::virt_node::combine(left.get_node(), right.get_node())) {
         m_input = acc::get_input(left);
         m_output = acc::get_output(right);
     }
Member Function Documentation
operator bool()
template<typename Input , typename Output = Input> tpie::pipelining::virtual_chunk_pull< Input, Output >::operator bool () const inline explicit noexcept
Test if it is not an empty chunk.
Definition at line 885 of file virtual.h.
{
         return m_input != nullptr;
     }
operator=()
template<typename Input , typename Output = Input> template<typename fact_t > virtual_chunk_pull& tpie::pipelining::virtual_chunk_pull< Input, Output >::operator= (pullpipe_middle< fact_t > && pipe) inline
Construct a node and assign it to this virtual chunk.
Definition at line 838 of file virtual.h.
{
         if (this->m_node) {
             log_error() << "Virtual chunk assigned twice" << std::endl;
             throw tpie::exception("Virtual chunk assigned twice");
         }
         typedef typename fact_t::template constructed_type<input_type> constructed_type;
         input_type temp(m_input);
         this->m_nodeMap = temp.get_node_map();
         fact_t f = std::move(pipe.factory);
         f.set_destination_kind_push();
         m_output = new bits::virtpullsrc_impl<constructed_type, Output>(f.construct(std::move(temp)));
         this->m_node = bits::virt_node::take_own(m_output);
         return *this;
     }
References tpie::pipelining::node::get_node_map(), tpie::log_error(), and tpie::pipelining::bits::virt_node::take_own().
operator|() [1/2]
template<typename Input , typename Output = Input> template<typename NextOutput > virtual_chunk_pull<Input, NextOutput> tpie::pipelining::virtual_chunk_pull< Input, Output >::operator| (virtual_chunk_pull< Output, NextOutput > dest) inline
Connect this virtual chunk to another chunk.
Definition at line 857 of file virtual.h.
{
         if (empty()) {
             return *bits::assert_types_equal_and_return<Input, Output, virtual_chunk_pull<Input, NextOutput> *>
                 ::go(&dest);
         }
         if (dest.empty()) {
             return *bits::assert_types_equal_and_return<Output, NextOutput, virtual_chunk_pull<Input, NextOutput> *>
                 ::go(this);
         }
         acc::get_input(dest)->set_source(get_output());
         return acc::construct<virtual_chunk_pull<Input, NextOutput>>(*this, dest);
     }
operator|() [2/2]
template<typename Input , typename Output = Input> virtual_chunk_pull_end<Input> tpie::pipelining::virtual_chunk_pull< Input, Output >::operator| (virtual_chunk_pull_end< Output > dest) inline
Connect this virtual chunk to another chunk.
Definition at line 873 of file virtual.h.
{
         if (empty()) {
             return *bits::assert_types_equal_and_return<Input, Output, virtual_chunk_pull_end<Input> *>
                 ::go(&dest);
         }
         acc::get_input(dest)->set_source(get_output());
         return acc::construct<virtual_chunk_pull_end<Input>>(*this, dest);
     }
The documentation for this class was generated from the following file:
pipelining/virtual.h