tpie::pipelining::bits::virt_node Class Reference
tpie::pipelining::bits::virt_node Class Reference
Ownership of nodes.
#include <tpie/pipelining/virtual.h>
Public Types
typedef std::shared_ptr< virt_node > ptr
Public Member Functions
void set_container (virtual_container *ctr)
Set and/or reset the virtual_container assigned to this virtual node.
Static Public Member Functions
static ptr take_own (node *pipe)
Take std::new-ownership of given node.
static ptr combine (ptr left, ptr right)
Aggregate ownership of virt_nodes.
Detailed Description
Ownership of nodes.
This class can only be instantiated through static methods that return a virt_node::ptr, providing reference counting so that nodes are only instantiated once each and are destroyed when the pipeline object goes out of scope.
This class either owns a node or two virt_nodes. The first case is used in the virtual_chunk constructors that accept a single pipe_base. The second case is used in the virtual_chunk pipe operators.
Definition at line 295 of file virtual.h.
Member Function Documentation
combine()
static ptr tpie::pipelining::bits::virt_node::combine (ptr left, ptr right) inline static
Aggregate ownership of virt_nodes.
Definition at line 319 of file virtual.h.
{
         virt_node * n = new virt_node();
         n->m_left = left;
         n->m_right = right;
         ptr res(n);
         return res;
     }
Referenced by tpie::pipelining::virtual_chunk_begin< Output >::operator|(), and tpie::pipelining::virtual_chunk_pull_begin< Output >::operator|().
set_container()
void tpie::pipelining::bits::virt_node::set_container (virtual_container * ctr) inline
Set and/or reset the virtual_container assigned to this virtual node.
Definition at line 331 of file virtual.h.
{
         m_container.reset(ctr);
     }
take_own()
static ptr tpie::pipelining::bits::virt_node::take_own (node * pipe) inline static
Take std::new-ownership of given node.
Definition at line 309 of file virtual.h.
{
         virt_node * n = new virt_node();
         n->m_node.reset(pipe);
         ptr res(n);
         return res;
     }
Referenced by tpie::pipelining::virtual_chunk_end< item_type >::operator=(), tpie::pipelining::virtual_chunk< Input, Output >::operator=(), tpie::pipelining::virtual_chunk_begin< Output >::operator=(), tpie::pipelining::virtual_chunk_pull_end< Input >::operator=(), tpie::pipelining::virtual_chunk_pull< Input, Output >::operator=(), and tpie::pipelining::virtual_chunk_pull_begin< Output >::operator=().
The documentation for this class was generated from the following file:
pipelining/virtual.h