tpie::job Class Reference
tpie::job Class Reference abstract
Inherited by tpie::parallel_sort_impl< iterator_type, comp_type, Progress, min_size >::qsort_job.
Public Member Functions
job ()
Default constructor.
virtual ~job ()
Default destructor.
virtual void operator() ()=0
Called by the worker thread.
void join ()
Wait for this job and its subjobs to complete.
bool is_done ()
Return true if this job and its subjobs are done.
void enqueue (job *parent=0)
Add this job to the job pool.
void run ()
Run this job.
Protected Member Functions
virtual void on_done ()
Called when this job and all subjobs are done.
Friends
class job_manager
The job manager needs to invoke run() on us.
Detailed Description
Definition at line 34 of file job.h.
Constructor & Destructor Documentation
job()
tpie::job::job ()
Default constructor.
~job()
virtual tpie::job::~job () inline virtual
Default destructor.
Definition at line 48 of file job.h.
 {}
Member Function Documentation
enqueue()
void tpie::job::enqueue (job * parent = 0)
Add this job to the job pool.
Parameters
parent (optional) The parent job, or 0 if this is a root job.
Referenced by tpie::parallel_sort_impl< iterator_type, comp_type, Progress, min_size >::qsort_job::operator()(), and tpie::parallel_sort_impl< iterator_type, comp_type, Progress, min_size >::operator()().
is_done()
bool tpie::job::is_done ()
Return true if this job and its subjobs are done.
join()
void tpie::job::join ()
Wait for this job and its subjobs to complete.
Referenced by tpie::parallel_sort_impl< iterator_type, comp_type, Progress, min_size >::operator()().
on_done()
virtual void tpie::job::on_done () inline protected virtual
Called when this job and all subjobs are done.
Reimplemented in tpie::parallel_sort_impl< iterator_type, comp_type, Progress, min_size >::qsort_job.
Definition at line 84 of file job.h.
 {}
operator()()
virtual void tpie::job::operator() () pure virtual
Called by the worker thread.
Implemented in tpie::parallel_sort_impl< iterator_type, comp_type, Progress, min_size >::qsort_job.
run()
void tpie::job::run ()
Run this job.
Invoke operator() and call done().
Friends And Related Function Documentation
job_manager
friend class job_manager friend
The job manager needs to invoke run() on us.
Definition at line 108 of file job.h.
The documentation for this class was generated from the following file:
job.h