tpie::array< T, Allocator > Class Template Reference
tpie::array< T, Allocator > Class Template Reference
A generic array with a fixed size.
#include <tpie/array.h>
Inherits tpie::linear_memory_base< array< T > >.
Public Types
typedef array_iter_base< T const, true > const_iterator
Iterator over a const array.
typedef array_iter_base< T const, false > const_reverse_iterator
Reverse iterator over a const array.
typedef array_iter_base< T, true > iterator
Iterator over an array.
typedef array_iter_base< T, false > reverse_iterator
Reverse iterator over an array.
typedef T value_type
Type of values containd in the array.
Public Member Functions
iterator find (size_t idx) throw ()
Return an iterator to the i'th element of the array.
const_iterator find (size_t idx) const throw ()
Return a const iterator to the i'th element of the array.
T & at (size_t i) throw ()
Return the element located at the given index.
const T & at (size_t i) const throw ()
Return the element located at the given index.
array & operator= (const array &other)
Copy elements from another array into this.
array & operator= (array &&other)
Move elements from another array into this.
template<typename OtherAllocator >
array & operator= (const array< T, OtherAllocator > &other)
Copy elements from another array with any allocator into this.
bool empty () const
Check if the array is empty.
const T & operator[] (size_t i) const
Return a const reference to an array entry.
T & operator[] (size_t i)
Return a reference to an array entry.
bool operator== (const array &other) const
Compare if the other array has the same elements in the same order as this.
bool operator!= (const array &other) const
Check if two arrays differ.
iterator begin ()
Return an iterator to the beginning of the array.
const_iterator begin () const
Return a const iterator to the beginning of the array.
iterator end ()
Return an iterator to the end of the array.
const_iterator end () const
Return a const iterator to the end of the array.
const T & front () const
Return the first element in the array.
T & front ()
Return the first element in the array.
const T & back () const
Return the last element in the array.
T & back ()
Return the last element in the array.
reverse_iterator rbegin ()
Reverse iterator to beginning of reverse sequence.
const_reverse_iterator rbegin () const
Const reverse iterator to beginning of reverse sequence.
reverse_iterator rend ()
Reverse iterator to end of reverse sequence.
const_reverse_iterator rend () const
Const reverse iterator to end of reverse sequence.
array (size_type s, const T &value, const Allocator &alloc=Allocator())
Construct array of given size.
array (size_type s, memory_bucket_ref bucket)
array (memory_bucket_ref bucket)
array (size_type s=0, const Allocator &alloc=Allocator())
Construct array of given size.
array (const array &other)
Construct a copy of another array.
array (array &&other)
Move construct from another array.
array (const array_view_base< T > &view)
array (const array_view_base< const T > &view)
~array ()
Free up all memory used by the array.
void resize (size_t size, const T &elm)
Change the size of the array.
void swap (array &other)
Swap two arrays.
void resize (size_t s)
Change the size of the array.
size_type size () const
Return the size of the array.
T * get ()
Return a raw pointer to the array content.
const T * get () const
Return a raw pointer to the array content.
Allocator get_allocator () const
Return copy of the allocator.
Static Public Member Functions
static constexpr double memory_coefficient () noexcept
Return the memory coefficient of the structure.
static constexpr double memory_overhead () noexcept
Return the memory overhead of the structure.
static constexpr memory_size_type memory_usage (memory_size_type size) noexcept
Return the number of bytes required to create a data structure supporting a given number of elements.
static constexpr linear_memory_usage memory_usage () noexcept
static constexpr memory_size_type memory_fits (memory_size_type memory) noexcept
Return the maximum number of elements that can be contained in in the structure when it is allowed to fill a given number of bytes.
Friends
struct bits::allocator_usage< T, Allocator >
Detailed Description
template<typename T, typename Allocator = allocator<T>>
class tpie::array< T, Allocator >
A generic array with a fixed size.
This is almost the same as a real C-style T array but the memory management is better.
Template Parameters
T The type of element to contain.
alloc_t Allocator.
Definition at line 149 of file array.h.
Member Typedef Documentation
const_iterator
template<typename T , typename Allocator = allocator<T>> typedef array_iter_base<T const, true> tpie::array< T, Allocator >::const_iterator
Iterator over a const array.
Definition at line 152 of file array.h.
const_reverse_iterator
template<typename T , typename Allocator = allocator<T>> typedef array_iter_base<T const, false> tpie::array< T, Allocator >::const_reverse_iterator
Reverse iterator over a const array.
Definition at line 155 of file array.h.
iterator
template<typename T , typename Allocator = allocator<T>> typedef array_iter_base<T, true> tpie::array< T, Allocator >::iterator
Iterator over an array.
Definition at line 158 of file array.h.
reverse_iterator
template<typename T , typename Allocator = allocator<T>> typedef array_iter_base<T, false> tpie::array< T, Allocator >::reverse_iterator
Reverse iterator over an array.
Definition at line 161 of file array.h.
value_type
template<typename T , typename Allocator = allocator<T>> typedef T tpie::array< T, Allocator >::value_type
Type of values containd in the array.
Definition at line 164 of file array.h.
Constructor & Destructor Documentation
array() [1/4]
template<typename T , typename Allocator = allocator<T>> tpie::array< T, Allocator >::array (size_type s, const T & value, const Allocator & alloc = Allocator()) inline
Construct array of given size.
Parameters
s The number of elements in the array.
value Each entry of the array is initialized with this value.
Definition at line 413 of file array.h.
          : m_elements(0), m_size(0), m_tss_used(false), m_allocator(alloc)
         {resize(s, value);}
Referenced by tpie::array< tpie::file_stream< element_type > >::memory_overhead().
array() [2/4]
template<typename T , typename Allocator = allocator<T>> tpie::array< T, Allocator >::array (size_type s = 0, const Allocator & alloc = Allocator()) inline
Construct array of given size.
Parameters
s The number of elements in the array.
Definition at line 430 of file array.h.
                       : m_elements(0), m_size(0), m_tss_used(false),
                         m_allocator(alloc) {resize(s);}
array() [3/4]
template<typename T , typename Allocator = allocator<T>> tpie::array< T, Allocator >::array (const array< T, Allocator > & other) inline
Construct a copy of another array.
Parameters
other The array to copy.
Definition at line 438 of file array.h.
                               : m_elements(0), m_size(other.m_size), m_tss_used(false), m_allocator(other.m_allocator) {
         if (other.size() == 0) return;
         alloc_copy(other.m_elements);
     }
array() [4/4]
template<typename T , typename Allocator = allocator<T>> tpie::array< T, Allocator >::array (array< T, Allocator > && other) inline
Move construct from another array.
Parameters
other The array to move.
Definition at line 447 of file array.h.
         : m_elements(other.m_elements)
         , m_size(other.m_size)
         , m_tss_used(other.m_tss_used)
         , m_allocator(other.m_allocator) {
         other.m_elements = nullptr;
         other.m_size = 0;
         other.m_tss_used = false;
     }
~array()
template<typename T , typename Allocator = allocator<T>> tpie::array< T, Allocator >::~array () inline
Free up all memory used by the array.
Definition at line 478 of file array.h.
 {resize(0);}
Member Function Documentation
at() [1/2]
template<typename T , typename Allocator = allocator<T>> T& tpie::array< T, Allocator >::at (size_t i) throw () inline
Return the element located at the given index.
Parameters
i The index of the element returned.
Definition at line 193 of file array.h.
{
         assert(i < size());
         return m_elements[i];
     }
Referenced by tpie::array< tpie::file_stream< element_type > >::back(), tpie::array< tpie::file_stream< element_type > >::front(), and tpie::array< tpie::file_stream< element_type > >::operator[]().
at() [2/2]
template<typename T , typename Allocator = allocator<T>> const T& tpie::array< T, Allocator >::at (size_t i) const throw () inline
Return the element located at the given index.
Parameters
i The index of the element returned.
Definition at line 201 of file array.h.
{
         assert(i < size());
         return m_elements[i];
     }
back() [1/2]
template<typename T , typename Allocator = allocator<T>> T& tpie::array< T, Allocator >::back () inline
Return the last element in the array.
Definition at line 353 of file array.h.
 {return at(size()-1);}
back() [2/2]
template<typename T , typename Allocator = allocator<T>> const T& tpie::array< T, Allocator >::back () const inline
Return the last element in the array.
Definition at line 348 of file array.h.
 {return at(size()-1);}
begin() [1/2]
template<typename T , typename Allocator = allocator<T>> iterator tpie::array< T, Allocator >::begin () inline
Return an iterator to the beginning of the array.
Returns
An iterator to the beginning of the array.
Definition at line 312 of file array.h.
 {return get_iter(0);}
Referenced by tpie::internal_vector< T >::begin(), tpie::disjoint_sets< value_t >::clear(), tpie::internal_priority_queue< tpie::ami::heap_ptr< REC >, comp >::make_safe(), tpie::internal_priority_queue< tpie::ami::heap_ptr< REC >, comp >::pop(), tpie::internal_priority_queue< tpie::ami::heap_ptr< REC >, comp >::pop_and_push(), tpie::internal_priority_queue< tpie::ami::heap_ptr< REC >, comp >::push(), tpie::serialize(), and tpie::unserialize().
begin() [2/2]
template<typename T , typename Allocator = allocator<T>> const_iterator tpie::array< T, Allocator >::begin () const inline
Return a const iterator to the beginning of the array.
Returns
A const iterator to the beginning of the array.
Definition at line 319 of file array.h.
 {return get_iter(0);}
empty()
template<typename T , typename Allocator = allocator<T>> bool tpie::array< T, Allocator >::empty () const inline
Check if the array is empty.
Returns
True if and only if size is 0.
Definition at line 258 of file array.h.
 {return size() == 0;}
end() [1/2]
template<typename T , typename Allocator = allocator<T>> iterator tpie::array< T, Allocator >::end () inline
Return an iterator to the end of the array.
Returns
An iterator to the end of the array.
Definition at line 326 of file array.h.
 {return get_iter(size());}
Referenced by tpie::disjoint_sets< value_t >::clear(), tpie::serialize(), and tpie::unserialize().
end() [2/2]
template<typename T , typename Allocator = allocator<T>> const_iterator tpie::array< T, Allocator >::end () const inline
Return a const iterator to the end of the array.
Returns
A const iterator to the end of the array.
Definition at line 333 of file array.h.
 {return get_iter(size());}
find() [1/2]
template<typename T , typename Allocator = allocator<T>> iterator tpie::array< T, Allocator >::find (size_t idx) throw () inline
Return an iterator to the i'th element of the array.
Parameters
idx The index of the element we want an iterator to.
Returns
An iterator to the i'th element.
Definition at line 172 of file array.h.
{
         assert(idx <= size());
         return get_iter(idx);
     }
Referenced by tpie::internal_vector< T >::end(), tpie::internal_priority_queue< tpie::ami::heap_ptr< REC >, comp >::insert(), tpie::internal_priority_queue< tpie::ami::heap_ptr< REC >, comp >::make_safe(), tpie::internal_priority_queue< tpie::ami::heap_ptr< REC >, comp >::pop(), tpie::internal_priority_queue< tpie::ami::heap_ptr< REC >, comp >::pop_and_push(), and tpie::internal_priority_queue< tpie::ami::heap_ptr< REC >, comp >::push().
find() [2/2]
template<typename T , typename Allocator = allocator<T>> const_iterator tpie::array< T, Allocator >::find (size_t idx) const throw () inline
Return a const iterator to the i'th element of the array.
Parameters
idx The index of the element we want an iterator to.
Returns
A const iterator to the i'th element.
Definition at line 183 of file array.h.
{
         assert(idx <= size());
         return get_iter(idx);
     }
front() [1/2]
template<typename T , typename Allocator = allocator<T>> T& tpie::array< T, Allocator >::front () inline
Return the first element in the array.
Definition at line 343 of file array.h.
 {return at(0);}
front() [2/2]
template<typename T , typename Allocator = allocator<T>> const T& tpie::array< T, Allocator >::front () const inline
Return the first element in the array.
Definition at line 338 of file array.h.
 {return at(0);}
get() [1/2]
template<typename T , typename Allocator = allocator<T>> T* tpie::array< T, Allocator >::get () inline
Return a raw pointer to the array content.
Definition at line 536 of file array.h.
 {return m_elements;}
Referenced by tpie::compressor_buffer::get(), and tpie::bits::serialization_reader_base::read().
get() [2/2]
template<typename T , typename Allocator = allocator<T>> const T* tpie::array< T, Allocator >::get () const inline
Return a raw pointer to the array content.
Definition at line 541 of file array.h.
 {return m_elements;}
get_allocator()
template<typename T , typename Allocator = allocator<T>> Allocator tpie::array< T, Allocator >::get_allocator () const inline
Return copy of the allocator.
Definition at line 546 of file array.h.
 {return m_allocator;}
memory_coefficient()
template<typename T , typename Allocator = allocator<T>> static constexpr double tpie::array< T, Allocator >::memory_coefficient () inline static constexpr noexcept
Return the memory coefficient of the structure.
Allocating a structure with n elements will use at most \(\lfloor \mathrm{memory\_coefficient} \cdot n + \mathrm{memory\_overhead} \rfloor \) bytes. This does not include memory overhead incurred if the structure is allocated using new.
Returns
The memory coefficient of the structure.
Definition at line 398 of file array.h.
{
         return (double)sizeof(T);
     }
Referenced by tpie::internal_queue< item_type >::memory_coefficient(), tpie::internal_stack_vector_base< T, internal_stack< T > >::memory_coefficient(), tpie::disjoint_sets< value_t >::memory_coefficient(), and tpie::internal_priority_queue< tpie::ami::heap_ptr< REC >, comp >::memory_coefficient().
memory_fits()
static constexpr memory_size_type tpie::linear_memory_base< array< T > >::memory_fits (memory_size_type memory) inline static constexpr noexcept inherited
Return the maximum number of elements that can be contained in in the structure when it is allowed to fill a given number of bytes.
Parameters
memory The number of bytes the structure is allowed to occupy
Returns
The number of elements that will fit in the structure
Definition at line 118 of file util.h.
{
         return static_cast<memory_size_type>(
             floor((memory - child_t::memory_overhead()) / child_t::memory_coefficient()));
     }
memory_overhead()
template<typename T , typename Allocator = allocator<T>> static constexpr double tpie::array< T, Allocator >::memory_overhead () inline static constexpr noexcept
Return the memory overhead of the structure.
See also
memory_coefficient()
Returns
The memory overhead.
Definition at line 405 of file array.h.
 {return sizeof(array);}
Referenced by tpie::internal_queue< item_type >::memory_overhead(), tpie::internal_stack_vector_base< T, internal_stack< T > >::memory_overhead(), tpie::disjoint_sets< value_t >::memory_overhead(), and tpie::internal_priority_queue< tpie::ami::heap_ptr< REC >, comp >::memory_overhead().
memory_usage()
static constexpr memory_size_type tpie::linear_memory_base< array< T > >::memory_usage (memory_size_type size) inline static constexpr noexcept inherited
Return the number of bytes required to create a data structure supporting a given number of elements.
Parameters
size The number of elements to support
Returns
The amount of memory required in bytes
Definition at line 106 of file util.h.
{
         return static_cast<memory_size_type>(
             floor(static_cast<double>(size) * child_t::memory_coefficient() + child_t::memory_overhead()));
     }
operator!=()
template<typename T , typename Allocator = allocator<T>> bool tpie::array< T, Allocator >::operator!= (const array< T, Allocator > & other) const inline
Check if two arrays differ.
Parameters
other The array to compare against.
Returns
False if they are equal; otherwise true.
Definition at line 301 of file array.h.
{
         if (size() != other.size()) return true;
         for (size_t i=0; i<size(); ++i) if (*get_iter(i) != *other.get_iter(i)) return true;
         return false;
     }
operator=() [1/3]
template<typename T , typename Allocator = allocator<T>> array& tpie::array< T, Allocator >::operator= (array< T, Allocator > && other) inline
Move elements from another array into this.
Note: This array is resized to the size of other.
Parameters
other The array to copy from.
Returns
A reference to this array.
Definition at line 228 of file array.h.
{
         resize(0);
         std::swap(m_allocator, other.m_allocator);
         std::swap(m_elements, other.m_elements);
         std::swap(m_size, other.m_size);
         std::swap(m_tss_used, other.m_tss_used);
         return *this;
     }
operator=() [2/3]
template<typename T , typename Allocator = allocator<T>> array& tpie::array< T, Allocator >::operator= (const array< T, Allocator > & other) inline
Copy elements from another array into this.
Note: This array is resized to the size of other.
Parameters
other The array to copy from.
Returns
A reference to this array.
Definition at line 214 of file array.h.
{
         resize(other.size());
         for (size_t i=0; i < size(); ++i) m_elements[i] = other[i];
         return *this;
     }
operator=() [3/3]
template<typename T , typename Allocator = allocator<T>> template<typename OtherAllocator > array& tpie::array< T, Allocator >::operator= (const array< T, OtherAllocator > & other) inline
Copy elements from another array with any allocator into this.
Note: This array is resized to the size of other.
Parameters
other The array to copy from.
Template Parameters
OtherAllocator The allocator used by the other array.
Returns
A reference to this array.
Definition at line 247 of file array.h.
{
         resize(other.size());
         for (size_t i=0; i < size(); ++i) m_elements[i] = other[i];
         return *this;
     }
operator==()
template<typename T , typename Allocator = allocator<T>> bool tpie::array< T, Allocator >::operator== (const array< T, Allocator > & other) const inline
Compare if the other array has the same elements in the same order as this.
Parameters
other The array to compare against.
Returns
True if they are equal otherwise false.
Definition at line 289 of file array.h.
{
         if (size() != other.size()) return false;
         for (size_t i=0;i<size();++i) if (*get_iter(i) != *other.get_iter(i)) return false;
         return true;
     }
operator[]() [1/2]
template<typename T , typename Allocator = allocator<T>> T& tpie::array< T, Allocator >::operator[] (size_t i) inline
Return a reference to an array entry.
Parameters
i The index of the entry to return.
Returns
Reference to the entry.
Definition at line 277 of file array.h.
{
         assert(i < size());
         return at(i);
     }
operator[]() [2/2]
template<typename T , typename Allocator = allocator<T>> const T& tpie::array< T, Allocator >::operator[] (size_t i) const inline
Return a const reference to an array entry.
Parameters
i The index of the entry to return.
Returns
Const reference to the entry.
Definition at line 266 of file array.h.
{
         assert(i < size());
         return at(i);
     }
rbegin() [1/2]
template<typename T , typename Allocator = allocator<T>> reverse_iterator tpie::array< T, Allocator >::rbegin () inline
Reverse iterator to beginning of reverse sequence.
Definition at line 358 of file array.h.
 {return get_rev_iter(0);}
rbegin() [2/2]
template<typename T , typename Allocator = allocator<T>> const_reverse_iterator tpie::array< T, Allocator >::rbegin () const inline
Const reverse iterator to beginning of reverse sequence.
Definition at line 363 of file array.h.
 {return get_rev_iter(0);}
rend() [1/2]
template<typename T , typename Allocator = allocator<T>> reverse_iterator tpie::array< T, Allocator >::rend () inline
Reverse iterator to end of reverse sequence.
Definition at line 368 of file array.h.
 {return get_rev_iter(size());}
rend() [2/2]
template<typename T , typename Allocator = allocator<T>> const_reverse_iterator tpie::array< T, Allocator >::rend () const inline
Const reverse iterator to end of reverse sequence.
Definition at line 373 of file array.h.
 {return get_rev_iter(size());}
resize() [1/2]
template<typename T , typename Allocator = allocator<T>> void tpie::array< T, Allocator >::resize (size_t s) inline
Change the size of the array.
All elements are lost.
Memory manager MUST be initialized at this point unless s == 0.
Parameters
s The new size of the array.
Definition at line 520 of file array.h.
{
         destruct_and_dealloc();
         m_size = s;
         alloc_dfl();
     }
resize() [2/2]
template<typename T , typename Allocator = allocator<T>> void tpie::array< T, Allocator >::resize (size_t size, const T & elm) inline
Change the size of the array.
All elements are lost.
Memory manager MUST be initialized at this point unless s == 0.
Parameters
size The new size of the array.
elm The initialization element.
Definition at line 490 of file array.h.
{
         if (size != m_size) {
             destruct_and_dealloc();
             m_size = size;
             alloc_fill(elm);
         } else {
             std::fill(m_elements+0, m_elements+m_size, elm);
         }
     }
Referenced by tpie::array< tpie::file_stream< element_type > >::array(), tpie::merge_sorter< T, UseProgress, pred_t, store_t >::begin(), tpie::pipelining::parallel_bits::producer< T1, T2 >::begin(), tpie::merge_sorter< T, UseProgress, pred_t, store_t >::end(), tpie::pipelining::parallel_bits::producer< T1, T2 >::end(), tpie::serialization_bits::internal_sort< T, std::less< T > >::free(), tpie::internal_queue< item_type >::internal_queue(), tpie::array< tpie::file_stream< element_type > >::operator=(), tpie::merge_sorter< T, UseProgress, pred_t, store_t >::pull(), tpie::internal_queue< item_type >::resize(), tpie::internal_stack_vector_base< T, internal_stack< T > >::resize(), tpie::disjoint_sets< value_t >::resize(), tpie::internal_priority_queue< tpie::ami::heap_ptr< REC >, comp >::resize(), tpie::compressor_buffer::set_capacity(), tpie::unserialize(), and tpie::array< tpie::file_stream< element_type > >::~array().
size()
template<typename T , typename Allocator = allocator<T>> size_type tpie::array< T, Allocator >::size () const inline
Return the size of the array.
Returns
The size of the array.
Definition at line 531 of file array.h.
 {return m_size;}
Referenced by tpie::array< tpie::file_stream< element_type > >::array(), tpie::array< tpie::file_stream< element_type > >::at(), tpie::internal_queue< item_type >::back(), tpie::array< tpie::file_stream< element_type > >::back(), tpie::compressor_buffer::capacity(), tpie::array< tpie::file_stream< element_type > >::empty(), tpie::array< tpie::file_stream< element_type > >::end(), tpie::merge_sorter< T, UseProgress, pred_t, store_t >::end(), tpie::array< tpie::file_stream< element_type > >::find(), tpie::internal_queue< item_type >::front(), tpie::internal_queue< item_type >::full(), tpie::array< tpie::file_stream< element_type > >::operator!=(), tpie::array< tpie::file_stream< element_type > >::operator=(), tpie::array< tpie::file_stream< element_type > >::operator==(), tpie::array< tpie::file_stream< element_type > >::operator[](), tpie::internal_queue< item_type >::push(), tpie::stack< item_type >::push(), tpie::internal_priority_queue< tpie::ami::heap_ptr< REC >, comp >::push(), tpie::serialization_bits::internal_sort< T, std::less< T > >::push(), tpie::array< tpie::file_stream< element_type > >::rend(), tpie::array< tpie::file_stream< element_type > >::resize(), and tpie::serialize().
swap()
template<typename T , typename Allocator = allocator<T>> void tpie::array< T, Allocator >::swap (array< T, Allocator > & other) inline
Swap two arrays.
Definition at line 504 of file array.h.
{
         std::swap(m_allocator, other.m_allocator);
         std::swap(m_elements, other.m_elements);
         std::swap(m_size, other.m_size);
         std::swap(m_tss_used, other.m_tss_used);
     }
Referenced by tpie::merge_sorter< T, UseProgress, pred_t, store_t >::end(), and std::swap().
The documentation for this class was generated from the following file:
array.h