tpie::file_accessor::byte_stream_accessor< file_accessor_t > Class Template Reference
tpie::file_accessor::byte_stream_accessor< file_accessor_t > Class Template Reference
Inherits tpie::file_accessor::stream_accessor_base< file_accessor_t >.
Public Member Functions
virtual memory_size_type read_block (void *, stream_size_type, memory_size_type) override
Read the given number of items from the given block into the given buffer.
virtual void write_block (const void *, stream_size_type, memory_size_type) override
Write the given number of items from the given buffer into the given block.
void set_size (stream_size_type amt)
bool empty ()
stream_size_type file_size ()
void truncate_bytes (stream_size_type size)
void write (const stream_size_type byteOffset, const void *data, const memory_size_type size)
void append (const void *data, memory_size_type size)
memory_size_type read (const stream_size_type byteOffset, void *data, memory_size_type size)
memory_size_type block_items () const
memory_size_type block_size () const
void open (const std::string &path, bool read, bool write, memory_size_type itemSize, memory_size_type blockSize, memory_size_type maxUserDataSize, cache_hint cacheHint, int compressionFlags)
Open file for reading and/or writing.
void close ()
memory_size_type read_user_data (void *data, memory_size_type count)
Read user data into the given buffer.
void write_user_data (const void *data, memory_size_type count)
Write user data to the stream.
stream_size_type size () const
Number of items in stream.
const std::string & path () const
Path of the file currently open.
memory_size_type user_data_size () const
Size (in bytes) of the user data.
memory_size_type max_user_data_size () const
Maximum size (in bytes) of the user data.
stream_size_type byte_size () const
Size (in bytes) of entire stream as laid out on disk after padding the final block to alignment boundary, including the header and user data.
void truncate (stream_size_type items)
void set_last_block_read_offset (stream_size_type n)
stream_size_type get_last_block_read_offset ()
bool get_compressed ()
int get_compression_flags ()
Static Public Member Functions
static memory_size_type memory_usage ()
Return memory usage of this file accessor.
Protected Member Functions
memory_size_type boundary () const
Returns the boundary on which we align blocks.
memory_size_type align_to_boundary (memory_size_type z) const
Given a memory offset, rounds up to the nearest alignment boundary.
memory_size_type header_size () const
The size of header and user data with padding included.
memory_size_type item_size () const
Protected Attributes
file_accessor_t m_fileAccessor
Detailed Description
template<typename file_accessor_t>
class tpie::file_accessor::byte_stream_accessor< file_accessor_t >
Definition at line 31 of file byte_stream_accessor.h.
Member Function Documentation
align_to_boundary()
template<typename file_accessor_t > memory_size_type tpie::file_accessor::stream_accessor_base< file_accessor_t >::align_to_boundary (memory_size_type z) const inline protected inherited
Given a memory offset, rounds up to the nearest alignment boundary.
Definition at line 97 of file stream_accessor_base.h.
 { return (z+boundary()-1)/boundary()*boundary(); }
References tpie::file_accessor::stream_accessor_base< file_accessor_t >::boundary().
Referenced by tpie::file_accessor::stream_accessor_base< file_accessor_t >::header_size().
boundary()
template<typename file_accessor_t > memory_size_type tpie::file_accessor::stream_accessor_base< file_accessor_t >::boundary () const inline protected inherited
Returns the boundary on which we align blocks.
Definition at line 91 of file stream_accessor_base.h.
 { return 4096; }
Referenced by tpie::file_accessor::stream_accessor_base< file_accessor_t >::align_to_boundary().
byte_size()
template<typename file_accessor_t > stream_size_type tpie::file_accessor::stream_accessor_base< file_accessor_t >::byte_size () const inline inherited
Size (in bytes) of entire stream as laid out on disk after padding the final block to alignment boundary, including the header and user data.
Definition at line 204 of file stream_accessor_base.h.
{
         return ((m_size + m_blockItems - 1)/m_blockItems) * m_blockSize + header_size();
     }
References tpie::file_accessor::stream_accessor_base< file_accessor_t >::header_size().
header_size()
template<typename file_accessor_t > memory_size_type tpie::file_accessor::stream_accessor_base< file_accessor_t >::header_size () const inline protected inherited
The size of header and user data with padding included.
This is the offset at which the first logical block begins.
Definition at line 103 of file stream_accessor_base.h.
 { return align_to_boundary(sizeof(stream_header_t)+m_maxUserDataSize); }
References tpie::file_accessor::stream_accessor_base< file_accessor_t >::align_to_boundary().
Referenced by tpie::file_accessor::stream_accessor_base< file_accessor_t >::byte_size(), tpie::file_accessor::stream_accessor< file_accessor_t >::read_block(), and tpie::file_accessor::stream_accessor< file_accessor_t >::write_block().
max_user_data_size()
template<typename file_accessor_t > memory_size_type tpie::file_accessor::stream_accessor_base< file_accessor_t >::max_user_data_size () const inline inherited
Maximum size (in bytes) of the user data.
Definition at line 197 of file stream_accessor_base.h.
 {return m_maxUserDataSize;}
Referenced by tpie::file_base_crtp< file_stream_base >::max_user_data_size().
memory_usage()
template<typename file_accessor_t > static memory_size_type tpie::file_accessor::stream_accessor_base< file_accessor_t >::memory_usage () inline static inherited
Return memory usage of this file accessor.
Definition at line 177 of file stream_accessor_base.h.
 {return sizeof(stream_accessor_base);}
Referenced by tpie::file< T >::memory_usage(), and tpie::uncompressed_stream< T >::memory_usage().
open()
template<typename file_accessor_t > void tpie::file_accessor::stream_accessor_base< file_accessor_t >::open (const std::string & path, bool read, bool write, memory_size_type itemSize, memory_size_type blockSize, memory_size_type maxUserDataSize, cache_hint cacheHint, int compressionFlags) inline inherited
Open file for reading and/or writing.
path()
template<typename file_accessor_t > const std::string& tpie::file_accessor::stream_accessor_base< file_accessor_t >::path () const inline inherited
Path of the file currently open.
Definition at line 187 of file stream_accessor_base.h.
 {return m_path;}
Referenced by tpie::file_base_crtp< file_stream_base >::path().
read_block()
template<typename file_accessor_t > virtual memory_size_type tpie::file_accessor::byte_stream_accessor< file_accessor_t >::read_block (void * data, stream_size_type blockNumber, memory_size_type itemCount) inline override virtual
Read the given number of items from the given block into the given buffer.
Parameters
data Buffer in which to store data. Must be able to hold at least sizeof(T)*itemCount bytes.
blockNumber Number of block in which to begin reading.
itemCount Number of items to read from beginning of given block. Must be less than m_blockItems.
Implements tpie::file_accessor::stream_accessor_base< file_accessor_t >.
Definition at line 34 of file byte_stream_accessor.h.
     {
         throw exception("Block operations not supported");
     }
read_user_data()
template<typename file_accessor_t > memory_size_type tpie::file_accessor::stream_accessor_base< file_accessor_t >::read_user_data (void * data, memory_size_type count) inline inherited
Read user data into the given buffer.
Parameters
data Buffer in which to store user data.
count Size of buffer, in bytes. The method will read at most this number of bytes.
Returns
Number of bytes of user data actually read, in case this is less than count.
Referenced by tpie::file_base_crtp< file_stream_base >::read_user_data().
size()
template<typename file_accessor_t > stream_size_type tpie::file_accessor::stream_accessor_base< file_accessor_t >::size () const inline inherited
Number of items in stream.
Definition at line 182 of file stream_accessor_base.h.
 {return m_size;}
Referenced by tpie::file_accessor::stream_accessor< file_accessor_t >::read_block(), and tpie::file_accessor::stream_accessor< file_accessor_t >::write_block().
user_data_size()
template<typename file_accessor_t > memory_size_type tpie::file_accessor::stream_accessor_base< file_accessor_t >::user_data_size () const inline inherited
Size (in bytes) of the user data.
Definition at line 192 of file stream_accessor_base.h.
 {return m_userDataSize;}
Referenced by tpie::file_base_crtp< file_stream_base >::user_data_size().
write_block()
template<typename file_accessor_t > virtual void tpie::file_accessor::byte_stream_accessor< file_accessor_t >::write_block (const void * data, stream_size_type blockNumber, memory_size_type itemCount) inline override virtual
Write the given number of items from the given buffer into the given block.
Parameters
data Buffer from which to write data. Must hold at least sizeof(T)*itemCount bytes of data.
blockNumber Number of block in which to write.
itemCount Number of items to write to beginning of given block. Must be less than m_blockItems.
Implements tpie::file_accessor::stream_accessor_base< file_accessor_t >.
Definition at line 41 of file byte_stream_accessor.h.
     {
         throw exception("Block operations not supported");
     }
write_user_data()
template<typename file_accessor_t > void tpie::file_accessor::stream_accessor_base< file_accessor_t >::write_user_data (const void * data, memory_size_type count) inline inherited
Write user data to the stream.
Parameters
data Buffer from which to write user data.
count Number of bytes to write. Cannot exceed max_user_data_size().
Referenced by tpie::file_base_crtp< file_stream_base >::write_user_data().
The documentation for this class was generated from the following file:
file_accessor/byte_stream_accessor.h