tpie::pipelining::bits::sort_factory< pred_t, store_t > Class Template Reference
tpie::pipelining::bits::sort_factory< pred_t, store_t > Class Template Reference
Inherits tpie::pipelining::factory_base.
Public Types
template<typename dest_t >
using constructed_type = sort_input_t< typename push_type< dest_t >::type, pred_t, store_t >
Public Member Functions
template<typename dest_t >
constructed_type< dest_t > construct (dest_t dest)
sort_factory (const pred_t &pred, store_t store)
void memory (double amount) noexcept
Set memory fraction for this node in the pipeline phase.
double memory () const noexcept
Set memory fraction for this node in the pipeline phase.
void hook_initialization (factory_init_hook *hook)
Add a node initialization hook.
void copy_hooks_to (factory_base &other) const
Copy the hooks that have been added to this factory to another.
void init_node (node &r)
\Brief Initialize node constructed in a subclass.
void init_sub_node (node &r)
Initialize node constructed in a subclass.
void add_default_edge (node &r, const node &dest) const
Used by pipe_base classes to set a default actor edge for ordinary push/pull nodes.
void add_default_edge (node &r, const node_token &dest) const
Used by pipe_base classes to set a default actor edge for ordinary push/pull nodes.
void add_node_set_edges (node &r) const
void name (const std::string &n, priority_type p)
Set name for this node.
void phase_name (const std::string &n, priority_type p)
Set name for this phase.
void push_breadcrumb (const std::string &n)
Set a prefix for the name of this node.
void set_destination_kind_push () noexcept
Used by pipe_base classes to indicate that the default actor edge is a push edge.
void set_destination_kind_pull () noexcept
Used by pipe_base classes to indicate that the default actor edge is a pull edge.
void add_to_set (node_set s)
void add_dependencies (node_set s)
void add_forwarding_dependencies (node_set s)
void forward (const std::string &key, any_noncopyable value)
Detailed Description
template<typename pred_t, typename store_t>
class tpie::pipelining::bits::sort_factory< pred_t, store_t >
Definition at line 394 of file sort.h.
Member Function Documentation
add_default_edge() [1/2]
void tpie::pipelining::factory_base::add_default_edge (node & r, const node & dest) const inherited
Used by pipe_base classes to set a default actor edge for ordinary push/pull nodes.
add_default_edge() [2/2]
void tpie::pipelining::factory_base::add_default_edge (node & r, const node_token & dest) const inherited
Used by pipe_base classes to set a default actor edge for ordinary push/pull nodes.
copy_hooks_to()
void tpie::pipelining::factory_base::copy_hooks_to (factory_base & other) const inherited
Copy the hooks that have been added to this factory to another.
hook_initialization()
void tpie::pipelining::factory_base::hook_initialization (factory_init_hook * hook) inherited
Add a node initialization hook.
When a node is instantiated in construct(), the given hook will get a chance to do some additional initialization.
init_node()
void tpie::pipelining::factory_base::init_node (node & r) inherited
\Brief Initialize node constructed in a subclass.
This lets the user define a name or memory fraction for this certain node in the pipeline phase, and it lets initialization hooks do their thing.
If more than one node is constructed in the subclass in construct(), the implementation should use init_sub_node instead.
init_sub_node()
void tpie::pipelining::factory_base::init_sub_node (node & r) inherited
Initialize node constructed in a subclass.
This lets the user define a name or memory fraction for this certain node in the pipeline phase, and it lets initialization hooks do their thing.
If just one node is constructed in the subclass in construct(), the implementation should use init_node instead.
memory() [1/2]
double tpie::pipelining::factory_base::memory () const inline noexcept inherited
Set memory fraction for this node in the pipeline phase.
In the absence of minimum and maximum memory requirements set by node implementations, the memory assigned to the node will be proportional to the amount parameter which sets the memory priority of this node in relation to the rest of the phase.
See also
factory_base::memory(double)
memory(double)
bits::pipe_base::memory()
Definition at line 99 of file factory_base.h.
{
         return m_amount;
     }
memory() [2/2]
void tpie::pipelining::factory_base::memory (double amount) inline noexcept inherited
Set memory fraction for this node in the pipeline phase.
In the absence of minimum and maximum memory requirements set by node implementations, the memory assigned to the node will be proportional to the amount parameter which sets the memory priority of this node in relation to the rest of the phase.
See also
factory_base::memory(double)
bits::pipe_base::memory(double)
Definition at line 87 of file factory_base.h.
{
         m_amount = amount;
         m_set = true;
     }
Referenced by tpie::pipelining::bits::pipe_base< pipe_begin< fact_t > >::memory().
name()
void tpie::pipelining::factory_base::name (const std::string & n, priority_type p) inline inherited
Set name for this node.
The name is used in the GraphViz plot generated by pipeline::plot.
The name priority given in the second argument should indicate how important this node is for the current phase, and is used in naming the progress indicator for this phase. The node with the highest priority name gets to name the entire phase.
See also
factory_base::name
bits::pipe_base::name
Definition at line 160 of file factory_base.h.
{
         m_name = n;
         m_namePriority = p;
     }
Referenced by tpie::pipelining::bits::pipe_base< pipe_begin< fact_t > >::name().
phase_name()
void tpie::pipelining::factory_base::phase_name (const std::string & n, priority_type p) inline inherited
Set name for this phase.
The maximal priority phase name given for a phase wins.
See also
factory_base::phase_name
bits::pipe_base::phase_name
Definition at line 171 of file factory_base.h.
{
         m_phaseName = n;
         m_phaseNamePriority = p;
     }
Referenced by tpie::pipelining::bits::pipe_base< pipe_begin< fact_t > >::phase_name().
push_breadcrumb()
void tpie::pipelining::factory_base::push_breadcrumb (const std::string & n) inline inherited
Set a prefix for the name of this node.
The name is used in the GraphViz plot generated by pipeline::plot.
See also
factory_base::push_breadcrumb
bits::pipe_base::breadcrumb
Definition at line 183 of file factory_base.h.
{
         if (m_breadcrumbs.empty()) m_breadcrumbs = n;
         else m_breadcrumbs = n + " | " + m_breadcrumbs;
     }
Referenced by tpie::pipelining::bits::pipe_base< pipe_begin< fact_t > >::breadcrumb().
set_destination_kind_pull()
void tpie::pipelining::factory_base::set_destination_kind_pull () inline noexcept inherited
Used by pipe_base classes to indicate that the default actor edge is a pull edge.
Definition at line 200 of file factory_base.h.
{
         m_destinationKind = destination_kind::pull;
     }
set_destination_kind_push()
void tpie::pipelining::factory_base::set_destination_kind_push () inline noexcept inherited
Used by pipe_base classes to indicate that the default actor edge is a push edge.
Definition at line 192 of file factory_base.h.
{
         m_destinationKind = destination_kind::push;
     }
Referenced by tpie::pipelining::pipe_middle< fact_t >::operator|().
The documentation for this class was generated from the following file:
pipelining/sort.h