tpie::serialization_reverse_reader Class Reference
tpie::serialization_reverse_reader Class Reference
Inherits tpie::bits::serialization_reader_base.
Public Member Functions
void open (std::string path)
void open (temp_file &tempFile)
bool can_read ()
stream_size_type offset ()
Number of bytes read, not including the header.
void close ()
void read (char *const s, const memory_size_type n)
Read n bytes from stream into buffer starting at s.
template<typename T >
void unserialize (T &v)
Unserialize an unserializable item from the stream.
template<typename IT >
void unserialize (IT a, IT b)
Unserialize a sequence of unserializable items from the stream.
stream_size_type file_size ()
Size of file in bytes, including the header.
stream_size_type size ()
Size of file in bytes, not including the header.
Static Public Member Functions
static memory_size_type block_size ()
static memory_size_type memory_usage ()
Protected Member Functions
void next_block () override
void open (std::string path, bool reverse)
void read_block (const stream_size_type blk)
Protected Attributes
tpie::array< char > m_block
stream_size_type m_size
memory_size_type m_index
memory_size_type m_blockSize
Detailed Description
Definition at line 385 of file serialization_stream.h.
Member Function Documentation
file_size()
stream_size_type tpie::bits::serialization_reader_base::file_size () inherited
Size of file in bytes, including the header.
offset()
stream_size_type tpie::serialization_reverse_reader::offset ()
Number of bytes read, not including the header.
For progress reporting.
Referenced by tpie::pipelining::serialization_bits::reverser_output_t< dest_t >::go().
read()
void tpie::bits::serialization_reader_base::read (char *const s, const memory_size_type n) inline inherited
Read n bytes from stream into buffer starting at s.
Parameters
s Buffer to contain the read data.
n Number of bytes to read.
Definition at line 287 of file serialization_stream.h.
{
         // TODO: inline some of this
         char * i = s;
         memory_size_type written = 0;
         while (written != n) {
             if (m_index >= m_blockSize) {
                 // virtual invocation
                 next_block();
             }
             memory_size_type remaining = n - written;
             memory_size_type blockRemaining = m_blockSize - m_index;
             memory_size_type readSize = std::min(remaining, blockRemaining);
             i = std::copy(m_block.get() + m_index,
                           m_block.get() + (m_index + readSize),
                           i);
             written += readSize;
             m_index += readSize;
         }
     }
References tpie::array< T, Allocator >::get().
size()
stream_size_type tpie::bits::serialization_reader_base::size () inherited
Size of file in bytes, not including the header.
For progress reporting.
Referenced by tpie::pipelining::serialization_bits::input_t< dest_t >::propagate(), tpie::pipelining::serialization_bits::reverser_output_t< dest_t >::propagate(), tpie::pipelining::serialization_bits::reverser_pull_output_t< T >::propagate(), tpie::pipelining::serialization_bits::buffer_output_t< dest_t >::propagate(), and tpie::pipelining::serialization_bits::buffer_pull_output_t< T >::propagate().
unserialize() [1/2]
template<typename IT > void tpie::bits::serialization_reader_base::unserialize (IT a, IT b) inline inherited
Unserialize a sequence of unserializable items from the stream.
A sequence of the given item type must exist at the current point in the stream.
The code stream.unserialize(a, b) just calls unserialize(stream, a, b) via ADL.
Definition at line 336 of file serialization_stream.h.
{
         using tpie::unserialize;
         unserialize(*this, a, b);
     }
References tpie::unserialize().
unserialize() [2/2]
template<typename T > void tpie::bits::serialization_reader_base::unserialize (T & v) inline inherited
Unserialize an unserializable item from the stream.
An item of the given type must exist at the current point in the stream.
The code stream.unserialize(v) just calls unserialize(stream, v) via ADL.
Definition at line 321 of file serialization_stream.h.
{
         using tpie::unserialize;
         unserialize(*this, v);
     }
References tpie::unserialize().
Referenced by tpie::pipelining::serialization_bits::input_t< dest_t >::go(), tpie::pipelining::serialization_bits::reverser_output_t< dest_t >::go(), and tpie::pipelining::serialization_bits::buffer_output_t< dest_t >::go().
The documentation for this class was generated from the following file:
serialization_stream.h