tpie::progress_indicator_null Class Reference
tpie::progress_indicator_null Class Reference
a dummy progress indicator that produces no output
#include <tpie/progress_indicator_null.h>
Inherits tpie::progress_indicator_base.
Public Member Functions
progress_indicator_null (stream_size_type range=0)
virtual void init (stream_size_type range)
Initialize progress indicator.
virtual void done ()
Advance the indicator to the end.
virtual void set_range (stream_size_type range)
Set the upper bound of the counting range.
virtual void refresh ()
Display the indicator.
void step (stream_size_type step=1)
Record an increment to the indicator and advance the indicator.
void raw_step (stream_size_type step)
Internal method used in fractional progress.
stream_size_type get_current ()
Get the current value of the step counter.
stream_size_type get_range ()
Get the maximum value of the current range.
execution_time_predictor * get_time_predictor ()
void set_time_predictor (execution_time_predictor *p)
std::string estimated_remaining_time ()
virtual void push_breadcrumb (const char *, description_importance)
virtual void pop_breadcrumb ()
Protected Attributes
stream_size_type m_range
The upper bound of the counting range.
stream_size_type m_current
The current progress count [m_minRange...m_maxRange].
Detailed Description
a dummy progress indicator that produces no output
Definition at line 39 of file progress_indicator_null.h.
Member Function Documentation
done()
virtual void tpie::progress_indicator_null::done () inline virtual
Advance the indicator to the end.
Reimplemented from tpie::progress_indicator_base.
Definition at line 47 of file progress_indicator_null.h.
 {}
get_current()
stream_size_type tpie::progress_indicator_base::get_current () inline inherited
Get the current value of the step counter.
Definition at line 152 of file progress_indicator_base.h.
 { return m_current; }
get_range()
stream_size_type tpie::progress_indicator_base::get_range () inline inherited
Get the maximum value of the current range.
Definition at line 157 of file progress_indicator_base.h.
 { return m_range; }
init()
virtual void tpie::progress_indicator_null::init (stream_size_type range) inline virtual
Initialize progress indicator.
Parameters
range The number of times step() is going to be called.
Reimplemented from tpie::progress_indicator_base.
Definition at line 46 of file progress_indicator_null.h.
 { unused(range); }
References tpie::unused().
raw_step()
void tpie::progress_indicator_base::raw_step (stream_size_type step) inline inherited
Internal method used in fractional progress.
In a hierarchy of fractional progress subindicators, only the lowest level of indicators should determine how many steps should pass until the next call to refresh(). When this happens, the subindicator calls raw_step() on its parent indicator rather than step(), which will short-circuit the logic and call the virtual method refresh() directly. You should probably not use this method; use step() instead.
Definition at line 111 of file progress_indicator_base.h.
{
         m_current += step;
         // Don't call call_refresh(); call refresh() directly instead.
         refresh();
     }
refresh()
virtual void tpie::progress_indicator_null::refresh () inline virtual
Display the indicator.
Implements tpie::progress_indicator_base.
Definition at line 49 of file progress_indicator_null.h.
 {}
set_range()
virtual void tpie::progress_indicator_null::set_range (stream_size_type range) inline virtual
Set the upper bound of the counting range.
This method also implies a reset of the counter. In order to be able to set the uper bound independent of setting the lower bound, no range checking is done.
Parameters
range The new upper bound.
Reimplemented from tpie::progress_indicator_base.
Definition at line 48 of file progress_indicator_null.h.
 { unused(range); }
References tpie::unused().
step()
void tpie::progress_indicator_base::step (stream_size_type step = 1) inline inherited
Record an increment to the indicator and advance the indicator.
Definition at line 91 of file progress_indicator_base.h.
{
         m_current += step;
         if (step >= m_remainingSteps) {
             call_refresh();
         } else {
             m_remainingSteps -= step;
         }
     }
Referenced by tpie::merge_sorter< T, UseProgress, pred_t, store_t >::calc(), and tpie::ami::Internal_Sorter_Obj< T, Compare >::sort().
Member Data Documentation
m_current
stream_size_type tpie::progress_indicator_base::m_current protected inherited
The current progress count [m_minRange...m_maxRange].
Definition at line 174 of file progress_indicator_base.h.
Referenced by tpie::progress_indicator_terminal::display_percentage(), tpie::progress_indicator_terminal::done(), tpie::progress_indicator_arrow::refresh(), tpie::progress_indicator_spin::refresh(), and tpie::progress_indicator_arrow::reset().
m_range
stream_size_type tpie::progress_indicator_base::m_range protected inherited
The upper bound of the counting range.
Definition at line 171 of file progress_indicator_base.h.
Referenced by tpie::progress_indicator_terminal::display_percentage(), tpie::progress_indicator_terminal::done(), and tpie::progress_indicator_arrow::refresh().
The documentation for this class was generated from the following file:
progress_indicator_null.h