tpie::progress_indicator_terminal Class Reference
tpie::progress_indicator_terminal Class Reference
A class that indicates the progress by a simple counter that is printed to the terminal.
#include <tpie/progress_indicator_terminal.h>
Inherits tpie::progress_indicator_base.
Inherited by tpie::progress_indicator_arrow, and tpie::progress_indicator_spin.
Public Member Functions
progress_indicator_terminal (const char *title, stream_size_type range, std::ostream &os=std::cout)
Initializes the indicator.
virtual ~progress_indicator_terminal ()
The destructor.
void done ()
Advance the indicator to the end.
void set_title (const std::string &title)
Set the title of a new task to be monitored.
virtual void refresh ()
Display the indicator.
void step (stream_size_type step=1)
Record an increment to the indicator and advance the indicator.
void raw_step (stream_size_type step)
Internal method used in fractional progress.
virtual void init (stream_size_type range=0)
Initialize progress indicator.
virtual void set_range (stream_size_type range)
Set the upper bound of the counting range.
stream_size_type get_current ()
Get the current value of the step counter.
stream_size_type get_range ()
Get the maximum value of the current range.
execution_time_predictor * get_time_predictor ()
void set_time_predictor (execution_time_predictor *p)
std::string estimated_remaining_time ()
virtual void push_breadcrumb (const char *, description_importance)
virtual void pop_breadcrumb ()
Protected Member Functions
void display_percentage ()
Compute and print the percentage or step count.
Protected Attributes
std::string m_title
A string holding the description of the title.
stream_size_type m_range
The upper bound of the counting range.
stream_size_type m_current
The current progress count [m_minRange...m_maxRange].
Detailed Description
A class that indicates the progress by a simple counter that is printed to the terminal.
Definition at line 40 of file progress_indicator_terminal.h.
Constructor & Destructor Documentation
progress_indicator_terminal()
tpie::progress_indicator_terminal::progress_indicator_terminal (const char * title, stream_size_type range, std::ostream & os = std::cout) inline
Initializes the indicator.
Parameters
title The title of the progress indicator. indicator.
range The lower bound of the range.
Definition at line 54 of file progress_indicator_terminal.h.
                                                                                                        :
         progress_indicator_base(range), m_title(title), m_os(os) {}
~progress_indicator_terminal()
virtual tpie::progress_indicator_terminal::~progress_indicator_terminal () inline virtual
The destructor.
Free the space allocated for title/description.
Definition at line 86 of file progress_indicator_terminal.h.
     {};
Member Function Documentation
display_percentage()
void tpie::progress_indicator_terminal::display_percentage () inline protected
Compute and print the percentage or step count.
Definition at line 139 of file progress_indicator_terminal.h.
     {
         //if (m_percentageUnit) {
         //  std::cout << std::setw(6) << std::setiosflags(std::ios::fixed) << std::setprecision(2)
         //           << ((static_cast<double>(m_current) * 100.0) /
         //               static_cast<double>(m_percentageUnit))
         //           << "%";
         //}
         //else {
         //      std::cout <<
         //}
         stream_size_type r = (m_current) * 100 / (m_range);
         m_os << r << '%';
     }
References tpie::progress_indicator_base::m_current, and tpie::progress_indicator_base::m_range.
Referenced by refresh().
done()
void tpie::progress_indicator_terminal::done () inline virtual
Advance the indicator to the end.
Reimplemented from tpie::progress_indicator_base.
Definition at line 95 of file progress_indicator_terminal.h.
                 {
         m_current = m_range;
         refresh();
         m_os << std::endl;
     }
References tpie::progress_indicator_base::m_current, tpie::progress_indicator_base::m_range, and refresh().
get_current()
stream_size_type tpie::progress_indicator_base::get_current () inline inherited
Get the current value of the step counter.
Definition at line 152 of file progress_indicator_base.h.
 { return m_current; }
get_range()
stream_size_type tpie::progress_indicator_base::get_range () inline inherited
Get the maximum value of the current range.
Definition at line 157 of file progress_indicator_base.h.
 { return m_range; }
init()
virtual void tpie::progress_indicator_base::init (stream_size_type range = 0) inline virtual inherited
Initialize progress indicator.
Parameters
range The number of times step() is going to be called.
Reimplemented in tpie::fractional_subindicator, tpie::progress_indicator_subindicator, and tpie::progress_indicator_null.
Definition at line 121 of file progress_indicator_base.h.
{
         if (range != 0) set_range(range);
         m_current = 0;
         call_refresh();
     }
Referenced by tpie::merge_sorter< T, UseProgress, pred_t, store_t >::calc(), and tpie::parallel_sort().
raw_step()
void tpie::progress_indicator_base::raw_step (stream_size_type step) inline inherited
Internal method used in fractional progress.
In a hierarchy of fractional progress subindicators, only the lowest level of indicators should determine how many steps should pass until the next call to refresh(). When this happens, the subindicator calls raw_step() on its parent indicator rather than step(), which will short-circuit the logic and call the virtual method refresh() directly. You should probably not use this method; use step() instead.
Definition at line 111 of file progress_indicator_base.h.
{
         m_current += step;
         // Don't call call_refresh(); call refresh() directly instead.
         refresh();
     }
refresh()
virtual void tpie::progress_indicator_terminal::refresh () inline virtual
Display the indicator.
Implements tpie::progress_indicator_base.
Reimplemented in tpie::progress_indicator_spin, and tpie::progress_indicator_arrow.
Definition at line 124 of file progress_indicator_terminal.h.
{
         m_os << '\r' << m_title << ' ';
         display_percentage();
         m_os << std::flush;
     }
References display_percentage(), and m_title.
Referenced by done().
set_range()
virtual void tpie::progress_indicator_base::set_range (stream_size_type range) inline virtual inherited
Set the upper bound of the counting range.
This method also implies a reset of the counter. In order to be able to set the uper bound independent of setting the lower bound, no range checking is done.
Parameters
range The new upper bound.
Reimplemented in tpie::progress_indicator_null.
Definition at line 140 of file progress_indicator_base.h.
{
         m_range = range;
     }
set_title()
void tpie::progress_indicator_terminal::set_title (const std::string & title) inline
Set the title of a new task to be monitored.
The terminal line will be newline'd, and the title will be followed by a newline as well.
Parameters
title The title of the new task to be monitored.
Definition at line 112 of file progress_indicator_terminal.h.
     {
         m_title = title;
         m_os << title << std::endl;
     }
References m_title.
step()
void tpie::progress_indicator_base::step (stream_size_type step = 1) inline inherited
Record an increment to the indicator and advance the indicator.
Definition at line 91 of file progress_indicator_base.h.
{
         m_current += step;
         if (step >= m_remainingSteps) {
             call_refresh();
         } else {
             m_remainingSteps -= step;
         }
     }
Referenced by tpie::merge_sorter< T, UseProgress, pred_t, store_t >::calc(), and tpie::ami::Internal_Sorter_Obj< T, Compare >::sort().
Member Data Documentation
m_current
stream_size_type tpie::progress_indicator_base::m_current protected inherited
The current progress count [m_minRange...m_maxRange].
Definition at line 174 of file progress_indicator_base.h.
Referenced by display_percentage(), done(), tpie::progress_indicator_arrow::refresh(), tpie::progress_indicator_spin::refresh(), and tpie::progress_indicator_arrow::reset().
m_range
stream_size_type tpie::progress_indicator_base::m_range protected inherited
The upper bound of the counting range.
Definition at line 171 of file progress_indicator_base.h.
Referenced by display_percentage(), done(), and tpie::progress_indicator_arrow::refresh().
m_title
std::string tpie::progress_indicator_terminal::m_title protected
A string holding the description of the title.
Definition at line 155 of file progress_indicator_terminal.h.
Referenced by tpie::progress_indicator_arrow::refresh(), refresh(), and set_title().
The documentation for this class was generated from the following file:
progress_indicator_terminal.h