tpie::array_view< T > Class Template Reference
tpie::array_view< T > Class Template Reference
Encapsulation of two pointers from any random access container.
#include <tpie/array_view.h>
Inherits tpie::array_view_base< T >.
Public Types
typedef T value_type
Type of values contained in the array.
Public Member Functions
array_view (const array_view &o)
Copy constructor.
template<typename A >
array_view (std::vector< T, A > &v)
std::vector constructor.
array_view (tpie::array< T > &v)
tpie::array constructor.
array_view (tpie::internal_vector< T > &v)
tpie::internal_vector constructor.
template<typename A >
array_view (std::vector< T, A > &v, size_t start, size_t end)
std::vector subsequence.
array_view (tpie::array< T > &v, size_t start, size_t end)
tpie::array subsequence.
array_view (T *start, T *end)
Pointer constructor.
array_view (T *start, size_t size)
Pointer+offset constructor.
iterator find (size_t idx) const throw ()
Return an iterator to the i'th element of the array.
T & at (size_t i) const throw ()
Return the element located at the given index.
bool empty () const
Check if the array is empty.
size_t size () const
Get number of elements in the array.
T & operator[] (size_t i) const
Return a reference to an array entry.
bool operator== (const array_view_base &other) const
Check if the other array has the same elements in the same order as this.
bool operator!= (const array_view_base &other) const
Check if the two arrays differ.
iterator begin () const
Return an iterator to the beginning of the array.
iterator end () const
Return an iterator to the end of the array.
T & front () const
Return the first element in the array.
T & back () const
Return the last element in the array.
Detailed Description
template<typename T>
class tpie::array_view< T >
Encapsulation of two pointers from any random access container.
Like std::vector, tpie::array and others, this class has begin(), end() iterators and front(), back() accessors. However, an array_view does not store data, it just stores pointers to data owned by other random access data structures. Passing around array_views, one avoids having the container type as a template parameter in one's code, but the code will still work with any supported random access container.
Definition at line 47 of file array_view.h.
Member Typedef Documentation
value_type
template<typename T > typedef T tpie::array_view_base< T >::value_type inherited
Type of values contained in the array.
Definition at line 74 of file array_view_base.h.
Constructor & Destructor Documentation
array_view() [1/8]
template<typename T > tpie::array_view< T >::array_view (const array_view< T > & o) inline
Copy constructor.
Definition at line 52 of file array_view.h.
                                            :
         array_view_base<T>(o) {}
array_view() [2/8]
template<typename T > template<typename A > tpie::array_view< T >::array_view (std::vector< T, A > & v) inline
std::vector constructor.
Definition at line 59 of file array_view.h.
                                           :
         array_view_base<T>(&*(v.begin()), &(*v.end())) {}
array_view() [3/8]
template<typename T > tpie::array_view< T >::array_view (tpie::array< T > & v) inline
tpie::array constructor.
Definition at line 65 of file array_view.h.
                                        :
         array_view_base<T>(&*(v.begin()), &(*v.end())) {}
array_view() [4/8]
template<typename T > tpie::array_view< T >::array_view (tpie::internal_vector< T > & v) inline
tpie::internal_vector constructor.
Definition at line 71 of file array_view.h.
                                                  :
         array_view_base<T>(&*(v.begin()), &(*v.end())) {}
array_view() [5/8]
template<typename T > template<typename A > tpie::array_view< T >::array_view (std::vector< T, A > & v, size_t start, size_t end) inline
std::vector subsequence.
Parameters
v The std::vector that stores the elements.
start The index of the first element of the view (such that view.front() == v[start]).
end Index past the last element of the view (such that view.back() == v[end-1]).
Definition at line 81 of file array_view.h.
                                                                     :
         array_view_base<T>(&v[start], &v[end]) {}
array_view() [6/8]
template<typename T > tpie::array_view< T >::array_view (tpie::array< T > & v, size_t start, size_t end) inline
tpie::array subsequence.
Parameters
v The tpie::array that stores the elements.
start The index of the first element of the view (such that view.front() == v[start]).
end Index past the last element of the view (such that view.back() == v[end-1]).
Definition at line 90 of file array_view.h.
                                                                  :
         array_view_base<T>(&v[start], &v[end]) {}
array_view() [7/8]
template<typename T > tpie::array_view< T >::array_view (T * start, T * end) inline
Pointer constructor.
The structure will produce the elements in the memory range [start, end).
Parameters
start Pointer to first element of the array_view.
end Pointer past the last element of the array_view.
Definition at line 97 of file array_view.h.
                                          :
         array_view_base<T>(start, end) {}
array_view() [8/8]
template<typename T > tpie::array_view< T >::array_view (T * start, size_t size) inline
Pointer+offset constructor.
The array_view will produce the elements in the memory range [start, start+size).
Parameters
start Pointer to first element of the array_view.
size Number of elements in the array_view.
Definition at line 106 of file array_view.h.
                                              :
         array_view_base<T>(start, start+size) {}
Member Function Documentation
at()
template<typename T > T& tpie::array_view_base< T >::at (size_t i) const throw () inline inherited
Return the element located at the given index.
Parameters
i The index of the element returned.
Definition at line 92 of file array_view_base.h.
{
         assert(i < size());
         return *find(i);
     }
Referenced by tpie::array_view_base< const T >::operator!=(), tpie::array_view_base< const T >::operator==(), and tpie::array_view_base< const T >::operator[]().
back()
template<typename T > T& tpie::array_view_base< T >::back () const inline inherited
Return the last element in the array.
Definition at line 168 of file array_view_base.h.
 {return *(m_end-1);}
begin()
template<typename T > iterator tpie::array_view_base< T >::begin () const inline inherited
Return an iterator to the beginning of the array.
Returns
An iterator to the beginning of the array.
Definition at line 151 of file array_view_base.h.
 {return iterator(m_start);}
empty()
template<typename T > bool tpie::array_view_base< T >::empty () const inline inherited
Check if the array is empty.
Returns
True if and only if size is 0.
Definition at line 102 of file array_view_base.h.
 {return m_end == m_start;}
end()
template<typename T > iterator tpie::array_view_base< T >::end () const inline inherited
Return an iterator to the end of the array.
Returns
An iterator to the end of the array.
Definition at line 158 of file array_view_base.h.
 {return iterator(m_end);}
find()
template<typename T > iterator tpie::array_view_base< T >::find (size_t idx) const throw () inline inherited
Return an iterator to the i'th element of the array.
Parameters
idx The index of the element we want an iterator to.
Returns
An iterator to the i'th element.
Definition at line 82 of file array_view_base.h.
{
         assert(idx <= size());
         return iterator(m_start + idx);
     }
Referenced by tpie::array_view_base< const T >::at().
front()
template<typename T > T& tpie::array_view_base< T >::front () const inline inherited
Return the first element in the array.
Definition at line 163 of file array_view_base.h.
 {return *m_start;}
operator!=()
template<typename T > bool tpie::array_view_base< T >::operator!= (const array_view_base< T > & other) const inline inherited
Check if the two arrays differ.
Parameters
other The array to compare against.
Returns
false If they are equal otherwise true.
Definition at line 140 of file array_view_base.h.
{
         if (size() != other.size()) return true;
         for (size_t i=0; i< size(); ++i) if (at(i) != other.at(i)) return true;
         return false;
     }
operator==()
template<typename T > bool tpie::array_view_base< T >::operator== (const array_view_base< T > & other) const inline inherited
Check if the other array has the same elements in the same order as this.
Parameters
other The array to compare against.
Returns
True if they are equal, otherwise false.
Definition at line 128 of file array_view_base.h.
{
         if (size() != other.size()) return false;
         for (size_t i=0; i < size(); ++i) if (at(i) != other.at(i)) return false;
         return true;
     }
operator[]()
template<typename T > T& tpie::array_view_base< T >::operator[] (size_t i) const inline inherited
Return a reference to an array entry.
Parameters
i The index of the entry to return.
Returns
Reference to the entry.
Definition at line 116 of file array_view_base.h.
{
         assert(i < size());
         return at(i);
     }
size()
template<typename T > size_t tpie::array_view_base< T >::size () const inline inherited
Get number of elements in the array.
Returns
Number of elements in the array.
Definition at line 108 of file array_view_base.h.
 {return m_end - m_start;}
Referenced by tpie::array_view_base< const T >::at(), tpie::pipelining::parallel_bits::consumer_impl< Input, Output, dest_t >::consume(), tpie::array_view_base< const T >::find(), tpie::array_view_base< const T >::operator!=(), tpie::array_view_base< const T >::operator==(), tpie::array_view_base< const T >::operator[](), and tpie::pipelining::parallel_bits::before_impl< dest_t >::push_all().
The documentation for this class was generated from the following file:
array_view.h