tpie::bbits::tree< T, O > Class Template Reference
tpie::bbits::tree< T, O > Class Template Reference
Augmented btree.
#include <tpie/btree/base.h>
Public Types
typedef tree_state< T, O > state_type
typedef state_type::augmenter_type augmenter_type
typedef state_type::value_type value_type
Type of value stored.
typedef state_type::keyextract_type keyextract_type
typedef state_type::augment_type augment_type
typedef state_type::key_type key_type
The type of key used.
typedef O::C comp_type
typedef state_type::store_type store_type
typedef btree_node< state_type > node_type
Type of node wrapper.
typedef store_type::size_type size_type
Type of the size.
typedef btree_iterator< state_type > iterator
Iterator type.
Public Member Functions
iterator begin () const
Returns an iterator pointing to the beginning of the tree.
iterator end () const
Returns an iterator pointing to the end of the tree.
template<typename NT >
void createNewRoot (NT left, NT right)
template<typename X = enab>
void insert_before (value_type v, const iterator &itr, enable< X, !is_static >=enab())
Insert given value into the btree before iterator.
template<typename X = enab>
void insert (value_type v, enable< X, !is_static >=enab())
Insert given value into the btree.
template<typename K , typename X = enab>
iterator find (K v, enable< X, is_ordered >=enab()) const
Return an iterator to the first item with the given key.
template<typename K , typename X = enab>
iterator lower_bound (K v, enable< X, is_ordered >=enab()) const
Return an interator to the first element that is "not less" than the given key.
template<typename K , typename X = enab>
iterator upper_bound (K v, enable< X, is_ordered >=enab()) const
Return an interator to the first element that is "greater" than the given key.
template<typename X = enab>
void erase (const iterator &itr, enable< X, !is_static >=enab())
remove item at iterator
template<typename X = enab>
size_type erase (key_type v, enable< X, !is_static &&is_ordered >=enab())
remove all items with given key
node_type root () const
Return the root node.
size_type size () const throw ()
Return the number of elements in the tree
bool empty () const throw ()
Check if the tree is empty.
void set_metadata (const std::string &data)
std::string get_metadata ()
template<typename X = enab>
tree (std::string path, comp_type comp=comp_type(), augmenter_type augmenter=augmenter_type(), enable< X, !is_internal >=enab())
Construct a btree with the given storage.
template<typename X = enab>
tree (comp_type comp=comp_type(), augmenter_type augmenter=augmenter_type(), memory_bucket_ref bucket=memory_bucket_ref(), enable< X, is_internal >=enab())
Construct a btree with the given storage.
const comp_type & comp () const
Static Public Attributes
static const bool is_internal = state_type::is_internal
static const bool is_static = state_type::is_static
static const bool is_ordered = state_type::is_ordered
Friends
class bbits::builder< T, O >
Detailed Description
template<typename T, typename O>
class tpie::bbits::tree< T, O >
Augmented btree.
External or internal augmented btree.
The fanout and location of nodes is decided by the store type S C is the item comparator type A is the type of the augmentation computation fuctor
Definition at line 238 of file base.h.
Member Typedef Documentation
iterator
template<typename T , typename O > typedef btree_iterator<state_type> tpie::bbits::tree< T, O >::iterator
Iterator type.
Definition at line 80 of file btree.h.
key_type
template<typename T , typename O > typedef state_type::key_type tpie::bbits::tree< T, O >::key_type
The type of key used.
Definition at line 60 of file btree.h.
node_type
template<typename T , typename O > typedef btree_node<state_type> tpie::bbits::tree< T, O >::node_type
Type of node wrapper.
Definition at line 70 of file btree.h.
size_type
template<typename T , typename O > typedef store_type::size_type tpie::bbits::tree< T, O >::size_type
Type of the size.
Definition at line 75 of file btree.h.
value_type
template<typename T , typename O > typedef state_type::value_type tpie::bbits::tree< T, O >::value_type
Type of value stored.
Definition at line 51 of file btree.h.
Constructor & Destructor Documentation
tree() [1/2]
template<typename T , typename O > template<typename X = enab> tpie::bbits::tree< T, O >::tree (std::string path, comp_type comp = comp_type(), augmenter_type augmenter = augmenter_type(), enable< X, !is_internal > = enab()) inline explicit
Construct a btree with the given storage.
Definition at line 597 of file btree.h.
                                                                                                                                           :
         m_state(store_type(path), std::move(augmenter), keyextract_type()),
         m_comp(comp) {}
tree() [2/2]
template<typename T , typename O > template<typename X = enab> tpie::bbits::tree< T, O >::tree (comp_type comp = comp_type(), augmenter_type augmenter = augmenter_type(), memory_bucket_ref bucket = memory_bucket_ref(), enable< X, is_internal > = enab()) inline explicit
Construct a btree with the given storage.
Definition at line 605 of file btree.h.
                                                   :
         m_state(store_type(bucket), std::move(augmenter), keyextract_type()),
         m_comp(comp) {}
Member Function Documentation
begin()
template<typename T , typename O > iterator tpie::bbits::tree< T, O >::begin () const inline
Returns an iterator pointing to the beginning of the tree.
Definition at line 270 of file btree.h.
{
         iterator i(&m_state);
         i.goto_begin();
         return i;
     }
empty()
template<typename T , typename O > bool tpie::bbits::tree< T, O >::empty () const throw () inline
Check if the tree is empty.
Definition at line 581 of file btree.h.
{
         return m_state.store().size() == 0;
     }
end()
template<typename T , typename O > iterator tpie::bbits::tree< T, O >::end () const inline
Returns an iterator pointing to the end of the tree.
Definition at line 279 of file btree.h.
{
         iterator i(&m_state);
         i.goto_end();
         return i;
     }
Referenced by tpie::bbits::tree< T, O >::erase().
erase() [1/2]
template<typename T , typename O > template<typename X = enab> void tpie::bbits::tree< T, O >::erase (const iterator & itr, enable< X, !is_static > = enab()) inline
remove item at iterator
Definition at line 461 of file btree.h.
{
         std::vector<internal_type> path=itr.m_path;
         leaf_type l = itr.m_leaf;
         size_t z = m_state.store().count(l);
         size_t i = itr.m_index;
         m_state.store().set_size(m_state.store().size()-1);
         --z;
         for (; i != z; ++i)
             m_state.store().move(l, i+1, l, i);
         m_state.store().set_count(l, z);
         // If we still have a large enough size
         if (z >= m_state.store().min_leaf_size()) {
             // We are the lone root
             if (path.empty()) {
                 augment_path(l);
                 return;
             }
             augment(l, path.back());
             augment_path(path);
             return;
         }
         // We are too small but the root
         if (path.empty()) {
             // We are now the empty tree
             if (z == 0) {
                 m_state.store().destroy(l);
                 m_state.store().set_height(0);
                 return;
             }
             augment_path(l);
             return;
         }
         // Steal or merge
         if (remove_fixup_round(l, path.back())) {
             augment_path(path);
             return;
         }
         // If l is now the only child of the root, make l the root
         if (path.size() == 1) {
             if (m_state.store().count(path.back()) == 1) {
                 l = m_state.store().get_child_leaf(path.back(), 0);
                 m_state.store().set_count(path.back(), 0);
                 m_state.store().destroy(path.back());
                 m_state.store().set_height(1);
                 m_state.store().set_root(l);
                 augment_path(l);
                 return;
             }
             augment_path(path);
             return;
         }
         while (true) {
             // We need to handle the parent
             internal_type p = path.back();
             path.pop_back();
             if (remove_fixup_round(p, path.back())) {
                 augment_path(path);
                 return;
             }
             if (path.size() == 1) {
                 if (m_state.store().count(path.back()) == 1) {
                     p = m_state.store().get_child_internal(path.back(), 0);
                     m_state.store().set_count(path.back(), 0);
                     m_state.store().destroy(path.back());
                     m_state.store().set_height(m_state.store().height()-1);
                     m_state.store().set_root(p);
                     path.clear();
                     path.push_back(p);
                     augment_path(path);
                     return;
                 }
                 augment_path(path);
                 return;
             }
         }
     }
Referenced by tpie::bbits::tree< T, O >::erase().
erase() [2/2]
template<typename T , typename O > template<typename X = enab> size_type tpie::bbits::tree< T, O >::erase (key_type v, enable< X, !is_static &&is_ordered > = enab()) inline
remove all items with given key
Definition at line 550 of file btree.h.
{
         size_type count = 0;
         iterator i = find(v);
         while(i != end()) {
             erase(i);
             ++count;
             i = find(v);
         }
         return count;
     }
References tpie::bbits::tree< T, O >::end(), tpie::bbits::tree< T, O >::erase(), and tpie::bbits::tree< T, O >::find().
find()
template<typename T , typename O > template<typename K , typename X = enab> iterator tpie::bbits::tree< T, O >::find (K v, enable< X, is_ordered > = enab()) const inline
Return an iterator to the first item with the given key.
Definition at line 379 of file btree.h.
{
         iterator itr(&m_state);
         if(m_state.store().height() == 0) {
             itr.goto_end();
             return itr;
         }
         std::vector<internal_type> path;
         leaf_type l = find_leaf<true>(path, v);
         size_t i=0;
         size_t z = m_state.store().count(l);
         while (true) {
             if (i == z) {
                 itr.goto_end();
                 return itr;
             }
             if (!m_comp(m_state.min_key(l, i), v) &&
                 !m_comp(v, m_state.min_key(l, i))) break;
             ++i;
         }
         itr.goto_item(path, l, i);
         return itr;
     }
Referenced by tpie::bbits::tree< T, O >::erase().
insert()
template<typename T , typename O > template<typename X = enab> void tpie::bbits::tree< T, O >::insert (value_type v, enable< X, !is_static > = enab()) inline
Insert given value into the btree.
Definition at line 371 of file btree.h.
{
         insert_before(v, upper_bound(m_state.m_augmenter.m_key_extract(v)));
     }
References tpie::bbits::tree< T, O >::insert_before(), and tpie::bbits::tree< T, O >::upper_bound().
insert_before()
template<typename T , typename O > template<typename X = enab> void tpie::bbits::tree< T, O >::insert_before (value_type v, const iterator & itr, enable< X, !is_static > = enab()) inline
Insert given value into the btree before iterator.
Definition at line 302 of file btree.h.
{
         m_state.store().set_size(m_state.store().size() + 1);
         // Handle the special case of the empty tree
         if (m_state.store().height() == 0) {
             leaf_type n = m_state.store().create_leaf();
             m_state.store().set_count(n, 1);
             m_state.store().set(n, 0, v);
             m_state.store().set_height(1);
             m_state.store().set_root(n);
             return;
         }
         const auto path = itr.m_path.data();
         auto index = itr.index();
         auto level = itr.m_path.size();
         //If there is room in the leaf
         if (m_state.store().count(itr.m_leaf) != m_state.store().max_leaf_size()) {
             insert_part(itr.m_leaf, v, index);
             if (level != 0) {
                 augment(itr.m_leaf, path[level-1]);
                 augment_path(path, level-1);
             }
             return;
         }
         // We split the leaf
         leaf_type l2 = split_and_insert(v, itr.m_leaf, index);
         // If the leaf was a root leaf we create a new root
         if (level == 0) {
             createNewRoot(itr.m_leaf, l2);
             return;
         }
         --level;
         index = m_state.store().index(itr.m_leaf, path[level]) + 1;
         augment(itr.m_leaf, path[level]);
         //If there is room in the parent to insert the extra leave
         if (m_state.store().count(path[level]) != m_state.store().max_internal_size()) {
             insert_part(path[level], l2, index);
             augment_path(path, level);
             return;
         }
         internal_type n2 = split_and_insert(l2, path[level], index);
         while (level != 0) {
             --level;
             index = m_state.store().index(path[level+1], path[level]) + 1;
             augment(path[level+1], path[level]);
             if (m_state.store().count(path[level]) != m_state.store().max_internal_size()) {
                 insert_part(path[level], n2, index);
                 augment_path(path, level);
                 return;
             }
             n2 = split_and_insert(n2, path[level], index);
         }
         //We need a new root
         createNewRoot(path[0], n2);
     }
Referenced by tpie::bbits::tree< T, O >::insert().
lower_bound()
template<typename T , typename O > template<typename K , typename X = enab> iterator tpie::bbits::tree< T, O >::lower_bound (K v, enable< X, is_ordered > = enab()) const inline
Return an interator to the first element that is "not less" than the given key.
Definition at line 410 of file btree.h.
{
         iterator itr(&m_state);
         if (m_state.store().height() == 0) {
             itr.goto_end();
             return itr;
         }
         std::vector<internal_type> path;
         leaf_type l = find_leaf(path, v);
         const size_t z = m_state.store().count(l);
         for (size_t i = 0 ; i < z ; ++i) {
             if (!m_comp(m_state.min_key(l, i), v)) {
                 itr.goto_item(path, l, i);
                 return itr;
             }
         }
         itr.goto_item(path, l, z-1);
         return ++itr;
     }
root()
template<typename T , typename O > node_type tpie::bbits::tree< T, O >::root () const inline
Return the root node.
Precondition
!empty()
Definition at line 566 of file btree.h.
{
         if (m_state.store().height() == 1) return node_type(&m_state, m_state.store().get_root_leaf());
         return node_type(&m_state, m_state.store().get_root_internal());
     }
size()
template<typename T , typename O > size_type tpie::bbits::tree< T, O >::size () const throw () inline
Return the number of elements in the tree
Definition at line 574 of file btree.h.
{
         return m_state.store().size();
     }
upper_bound()
template<typename T , typename O > template<typename K , typename X = enab> iterator tpie::bbits::tree< T, O >::upper_bound (K v, enable< X, is_ordered > = enab()) const inline
Return an interator to the first element that is "greater" than the given key.
Definition at line 436 of file btree.h.
{
         iterator itr(&m_state);
         if (m_state.store().height() == 0) {
             itr.goto_end();
             return itr;
         }
         std::vector<internal_type> path;
         leaf_type l = find_leaf<true>(path, v);
         const size_t z = m_state.store().count(l);
         for (size_t i = 0 ; i < z ; ++i) {
             if (m_comp(v, m_state.min_key(l, i))) {
                 itr.goto_item(path, l, i);
                 return itr;
             }
         }
         itr.goto_item(path, l, z-1);
         return ++itr;
     }
Referenced by tpie::bbits::tree< T, O >::insert().
The documentation for this class was generated from the following files:
btree/base.h
btree/btree.h