tpie::pipelining::bits::tee_t< dest_t, T > Class Template Reference
tpie::pipelining::bits::tee_t< dest_t, T > Class Template Reference
Inherits tpie::pipelining::node.
Public Types
typedef T item_type
enum PLOT { PLOT_SIMPLIFIED_HIDE =1, PLOT_BUFFERED =2, PLOT_PARALLEL =4 }
Options for how to plot this node.
enum STATE {
STATE_FRESH, STATE_IN_PREPARE, STATE_AFTER_PREPARE, STATE_IN_PROPAGATE,
STATE_AFTER_PROPAGATE, STATE_IN_BEGIN, STATE_AFTER_BEGIN, STATE_IN_GO,
STATE_IN_END, STATE_AFTER_END
}
Used internally to check order of method calls.
typedef boost::optional< any_noncopyable & > maybeany_t
Public Member Functions
tee_t (dest_t dest, file_stream< item_type > &fs)
void push (const item_type &i)
memory_size_type get_minimum_resource_usage (resource_type type) const
Get the minimum amount of the resource declared by this node.
memory_size_type get_maximum_resource_usage (resource_type type) const
Get the maximum amount of the resource declared by this node.
double get_resource_fraction (resource_type type) const
Get the priority for the specific resource of this node.
memory_size_type get_available_of_resource (resource_type type) const
Get the amount of the specific resource assigned to this node.
void set_minimum_resource_usage (resource_type type, memory_size_type usage)
Called by implementers to declare minimum resource requirements.
void set_maximum_resource_usage (resource_type type, memory_size_type usage)
Called by implementers to declare maximum resource requirements.
void set_resource_fraction (resource_type type, double f)
Set the resource priority of this node.
virtual void resource_available_changed (resource_type, memory_size_type)
Called by the resource manager to notify the node's available amount of resource has changed.
void _internal_set_available_of_resource (resource_type type, memory_size_type available)
Used internally to assign the available resource to the node.
memory_size_type get_minimum_memory () const
Get the minimum amount of memory declared by this node.
memory_size_type get_maximum_memory () const
Get the maximum amount of memory declared by this node.
double get_memory_fraction () const
Get the memory priority of this node.
memory_size_type get_available_memory () const
Get the amount of memory assigned to this node.
void set_minimum_memory (memory_size_type minimumMemory)
Called by implementers to declare minimum memory requirements.
void set_maximum_memory (memory_size_type maximumMemory)
Called by implementers to declare maximum memory requirements.
void set_memory_fraction (double f)
Set the memory priority of this node.
virtual void set_available_memory (memory_size_type availableMemory)
Called by the memory manager to set the amount of memory assigned to this node.
memory_size_type get_used_memory () const
Get the amount of memory currently used by this node.
bits::node_map::ptr get_node_map () const
Get the local node map, mapping node IDs to node pointers for all the nodes reachable from this one.
node_token::id_t get_id () const
Get the internal node ID of this node (mainly for debugging purposes).
virtual void prepare ()
Called before memory assignment but after depending phases have executed and ended.
virtual void propagate ()
Propagate stream metadata.
virtual void begin ()
Begin pipeline processing phase.
virtual bool is_go_free () const
virtual void go ()
For initiator nodes, execute this phase by pushing all items to be pushed.
virtual void end ()
End pipeline processing phase.
virtual bool can_evacuate ()
Overridden by nodes that have data to evacuate.
virtual void evacuate ()
Overridden by nodes that have data to evacuate.
priority_type get_name_priority ()
Get the priority of this node's name.
const std::string & get_name ()
Get this node's name.
void set_name (const std::string &name, priority_type priority=PRIORITY_USER)
Set this node's name.
priority_type get_phase_name_priority ()
Get the priority of this node's pdane name.
const std::string & get_phase_name ()
Get this node's phase name.
void set_phase_name (const std::string &name, priority_type priority=PRIORITY_USER)
Set this node's phase name.
void set_breadcrumb (const std::string &breadcrumb)
Used internally when a pair_factory has a name set.
stream_size_type get_steps ()
Used internally for progress indication.
stream_size_type get_steps_left ()
void set_progress_indicator (progress_indicator_base *pi)
Used internally. Set the progress indicator to use.
progress_indicator_base * get_progress_indicator ()
Used internally. Get the progress indicator used.
STATE get_state () const
Used internally to check order of method calls.
void set_state (STATE s)
Used internally to check order of method calls.
resource_type get_resource_being_assigned () const
Used internally to check order of method calls.
void set_resource_being_assigned (resource_type type)
Used internally to check order of method calls.
flags< PLOT > get_plot_options () const
Get options specified for plot(), as a combination of node::PLOT values.
void set_plot_options (flags< PLOT > options)
Set options specified for plot(), as a combination of node::PLOT values.
void add_push_destination (const node_token &dest)
Called by implementers to declare a push destination.
void add_push_destination (const node &dest)
Called by implementers to declare a push destination.
void add_pull_source (const node_token &dest)
Called by implementers to declare a pull source.
void add_pull_source (const node &dest)
Called by implementers to declare a pull source.
void add_dependency (const node_token &dest)
Called by implementers to declare a node dependency, that is, a requirement that another node has end() called before the begin() of this node.
void add_dependency (const node &dest)
Called by implementers to declare a node dependency, that is, a requirement that another node has end() called before the begin() of this node.
void add_memory_share_dependency (const node_token &dest)
Called by implementers to declare a node memory share dependency, that is, a requirement that another node has end() called before the begin() of this node, and memory shared between end() and begin() unless evacuate() is called.
void add_memory_share_dependency (const node &dest)
Called by implementers to declare a node memory share dependency, that is, a requirement that another node has end() called before the begin() of this node, and memory shared between end() and begin() unless evacuate() is called.
template<typename T >
void forward (std::string key, T value, memory_size_type k=std::numeric_limits< memory_size_type >::max())
Called by implementers to forward auxiliary data to successors.
void forward_any (std::string key, any_noncopyable value, memory_size_type k=std::numeric_limits< memory_size_type >::max())
See node::forward.
bool can_fetch (std::string key)
Find out if there is a piece of auxiliary data forwarded with a given name.
maybeany_t fetch_maybe (std::string key)
Fetch piece of auxiliary data as any_noncopyable (the internal representation) wrapped in a boost::optional which is unitialized if the key is not found.
any_noncopyable & fetch_any (std::string key)
Fetch piece of auxiliary data as any_noncopyable (the internal representation).
template<typename T >
T & fetch (std::string key)
Fetch piece of auxiliary data, expecting a given value type.
void no_forward_through ()
Dissablow forwards through this node.
const node_token & get_token () const
Get the node_token that maps this node's ID to a pointer to this.
void set_steps (stream_size_type steps)
Called by implementers that intend to call step().
void step (stream_size_type steps=1)
Step the progress indicator.
progress_indicator_base * proxy_progress_indicator ()
Get a non-initialized progress indicator for use with external implementations.
bool can_pull () const
For pull nodes, return true if there are more items to be pulled.
item_type pull ()
For pull nodes, pull the next item from this node.
void push (const item_type &item)
For push nodes, push the next item to this node.
void register_datastructure_usage (const std::string &name, double priority=1)
Registers a datastructure.
void set_datastructure_memory_limits (const std::string &name, memory_size_type min, memory_size_type max=std::numeric_limits< memory_size_type >::max())
Assign memory to a registered datastructure.
memory_size_type get_datastructure_memory (const std::string &name)
Returns the memory assigned to a datastructure.
template<typename T >
void set_datastructure (const std::string &name, T datastructure)
Returns a previously declared datastructure.
template<typename T >
T & get_datastructure (const std::string &name)
Returns a previously declared datastructure.
void unset_datastructure (const std::string &name)
size_t buckets () const
Count the number of memory buckets.
std::unique_ptr< memory_bucket > & bucket (size_t i)
Access a memory bucket.
tpie::memory_bucket_ref allocator (size_t i=0)
Return an allocator that counts memory usage within the node.
Detailed Description
template<typename dest_t, typename T>
class tpie::pipelining::bits::tee_t< dest_t, T >
Definition at line 331 of file file_stream.h.
Member Enumeration Documentation
PLOT
enum tpie::pipelining::node::PLOT inherited
Options for how to plot this node.
Definition at line 84 of file node.h.
               {
         PLOT_SIMPLIFIED_HIDE=1,
         PLOT_BUFFERED=2,
         PLOT_PARALLEL=4
     };
STATE
enum tpie::pipelining::node::STATE inherited
Used internally to check order of method calls.
Definition at line 93 of file node.h.
                {
         STATE_FRESH,
         STATE_IN_PREPARE,
         STATE_AFTER_PREPARE,
         STATE_IN_PROPAGATE,
         STATE_AFTER_PROPAGATE,
         STATE_IN_BEGIN,
         STATE_AFTER_BEGIN,
         STATE_IN_GO,
         STATE_IN_END,
         STATE_AFTER_END
     };
Member Function Documentation
_internal_set_available_of_resource()
void tpie::pipelining::node::_internal_set_available_of_resource (resource_type type, memory_size_type available) inherited
Used internally to assign the available resource to the node.
add_dependency() [1/2]
void tpie::pipelining::node::add_dependency (const node & dest) inherited
Called by implementers to declare a node dependency, that is, a requirement that another node has end() called before the begin() of this node.
add_dependency() [2/2]
void tpie::pipelining::node::add_dependency (const node_token & dest) inherited
Called by implementers to declare a node dependency, that is, a requirement that another node has end() called before the begin() of this node.
add_memory_share_dependency() [1/2]
void tpie::pipelining::node::add_memory_share_dependency (const node & dest) inherited
Called by implementers to declare a node memory share dependency, that is, a requirement that another node has end() called before the begin() of this node, and memory shared between end() and begin() unless evacuate() is called.
add_memory_share_dependency() [2/2]
void tpie::pipelining::node::add_memory_share_dependency (const node_token & dest) inherited
Called by implementers to declare a node memory share dependency, that is, a requirement that another node has end() called before the begin() of this node, and memory shared between end() and begin() unless evacuate() is called.
add_pull_source() [1/2]
void tpie::pipelining::node::add_pull_source (const node & dest) inherited
Called by implementers to declare a pull source.
add_pull_source() [2/2]
void tpie::pipelining::node::add_pull_source (const node_token & dest) inherited
Called by implementers to declare a pull source.
add_push_destination() [1/2]
void tpie::pipelining::node::add_push_destination (const node & dest) inherited
Called by implementers to declare a push destination.
add_push_destination() [2/2]
void tpie::pipelining::node::add_push_destination (const node_token & dest) inherited
Called by implementers to declare a push destination.
allocator()
tpie::memory_bucket_ref tpie::pipelining::node::allocator (size_t i = 0) inline inherited
Return an allocator that counts memory usage within the node.
Definition at line 787 of file node.h.
{
         return tpie::memory_bucket_ref(bucket(i).get());
     }
begin()
virtual void tpie::pipelining::node::begin () inline virtual inherited
Begin pipeline processing phase.
The implementation may pull() from a pull destination in begin(), and it may push() to a push destination.
The pipelining framework calls begin() on the nodes in the actor graph in a reverse topological order. The framework calls node::begin() on a node after calling begin() on its pull and push destinations.
The default implementation does nothing.
Reimplemented in tpie::pipelining::parallel_bits::producer< T1, T2 >, tpie::pipelining::bits::pull_unique_t< src_t, equal_t >, tpie::pipelining::bits::unique_t< dest_t, equal_t >, tpie::pipelining::bits::named_output_t< T >, tpie::pipelining::serialization_bits::buffer_input_t< T >, tpie::pipelining::bits::sort_output_t< pred_t, dest_t, store_t >, tpie::pipelining::serialization_bits::reverser_input_t< T >, tpie::pipelining::bits::sort_pull_output_t< T, pred_t, store_t >, tpie::pipelining::join< T >::sink_impl, tpie::pipelining::bits::buffer_input_t< T >, tpie::pipelining::bits::pull_peek_t< source_t >, tpie::pipelining::serialization_bits::sort_output_base< Traits >, tpie::pipelining::bits::pull_input_vector_t< T, A >, tpie::pipelining::bits::chunker_t< dest_t >, tpie::pipelining::bits::reverser_input_t< T >, tpie::pipelining::bits::ostream_logger_t< dest_t >, tpie::pipelining::bits::ami_input_t< dest_t >, tpie::pipelining::bits::virtpullrecv< T >, tpie::pipelining::bits::virtrecv< Output >, and tpie::pipelining::bits::virtrecv< T >.
Definition at line 298 of file node.h.
{
     }
Referenced by tpie::pipelining::bits::ostream_logger_t< dest_t >::begin().
bucket()
std::unique_ptr<memory_bucket>& tpie::pipelining::node::bucket (size_t i) inline inherited
Access a memory bucket.
Definition at line 778 of file node.h.
{
         if (m_buckets.size() <= i) m_buckets.resize(i+1);
         if (!m_buckets[i]) m_buckets[i].reset(new memory_bucket());
         return m_buckets[i];
     }
buckets()
size_t tpie::pipelining::node::buckets () const inline inherited
Count the number of memory buckets.
Definition at line 773 of file node.h.
 {return m_buckets.size();}
can_evacuate()
virtual bool tpie::pipelining::node::can_evacuate () inline virtual inherited
Overridden by nodes that have data to evacuate.
Definition at line 334 of file node.h.
{
         return false;
     }
can_fetch()
bool tpie::pipelining::node::can_fetch (std::string key) inline inherited
Find out if there is a piece of auxiliary data forwarded with a given name.
Definition at line 588 of file node.h.
{
         return bool(fetch_maybe(key));
     }
can_pull()
bool tpie::pipelining::node::can_pull () const inline inherited
For pull nodes, return true if there are more items to be pulled.
end()
virtual void tpie::pipelining::node::end () inline virtual inherited
End pipeline processing phase.
The implementation may pull() from a pull destination in end(), and it may push() to a push destination.
The pipelining framework calls end() on the nodes in the pipeline graph in a topological order. The framework calls node::end() on a node before its pull and push destinations.
The default implementation does nothing, so it does not matter if the implementation calls the parent end().
Reimplemented in tpie::pipelining::parallel_bits::producer< T1, T2 >, tpie::pipelining::serialization_bits::buffer_pull_output_t< T >, tpie::pipelining::serialization_bits::buffer_output_t< dest_t >, tpie::pipelining::bits::named_output_t< T >, tpie::pipelining::serialization_bits::buffer_input_t< T >, tpie::pipelining::bits::internal_reverser_pull_output_t< T >, tpie::pipelining::serialization_bits::reverser_pull_output_t< T >, tpie::pipelining::bits::named_pull_input_t< T >, tpie::pipelining::bits::reverser_pull_output_t< T >, tpie::pipelining::serialization_bits::reverser_output_t< dest_t >, tpie::pipelining::bits::sort_output_t< pred_t, dest_t, store_t >, tpie::pipelining::bits::pull_reverse_input_t< T >, tpie::pipelining::bits::internal_reverser_output_t< dest_t >, tpie::pipelining::bits::pull_input_t< T >, tpie::pipelining::serialization_bits::reverser_input_t< T >, tpie::pipelining::bits::buffer_output_t< dest_t >, tpie::pipelining::bits::sort_pull_output_t< T, pred_t, store_t >, tpie::pipelining::bits::reverser_output_t< dest_t >, tpie::pipelining::bits::buffer_input_t< T >, tpie::pipelining::serialization_bits::sort_output_base< Traits >, tpie::pipelining::bits::input_t< dest_t >, tpie::pipelining::bits::buffer_pull_output_t< T >, tpie::pipelining::bits::chunker_t< dest_t >, tpie::pipelining::bits::internal_buffer_pull_output_t< T >, tpie::pipelining::bits::reverser_input_t< T >, tpie::pipelining::bits::ordered_merge_t< dest_t, fact_t, comp_t >, tpie::pipelining::bits::ostream_logger_t< dest_t >, and tpie::pipelining::bits::count_consecutive_t< dest_t >.
Definition at line 328 of file node.h.
{
     }
Referenced by tpie::pipelining::bits::count_consecutive_t< dest_t >::end(), and tpie::pipelining::bits::ostream_logger_t< dest_t >::end().
evacuate()
virtual void tpie::pipelining::node::evacuate () inline virtual inherited
Overridden by nodes that have data to evacuate.
Definition at line 341 of file node.h.
{
     }
fetch()
template<typename T > T& tpie::pipelining::node::fetch (std::string key) inline inherited
Fetch piece of auxiliary data, expecting a given value type.
Definition at line 609 of file node.h.
{
         any_noncopyable &item = fetch_any(key);
         try {
             return any_cast<T>(item);
         } catch (const bad_any_noncopyable_cast & e) {
             std::stringstream ss;
             ss << "Trying to fetch key '" << key << "' of type "
                << typeid(T).name() << " but forwarded data was of type "
                << item.type().name() << ". Message was: " << e.what();
             throw invalid_argument_exception(ss.str());
         }
     }
fetch_any()
any_noncopyable& tpie::pipelining::node::fetch_any (std::string key) inherited
Fetch piece of auxiliary data as any_noncopyable (the internal representation).
fetch_maybe()
maybeany_t tpie::pipelining::node::fetch_maybe (std::string key) inherited
Fetch piece of auxiliary data as any_noncopyable (the internal representation) wrapped in a boost::optional which is unitialized if the key is not found.
forward()
template<typename T > void tpie::pipelining::node::forward (std::string key, T value, memory_size_type k = std::numeric_limits<memory_size_type>::max()) inline inherited
Called by implementers to forward auxiliary data to successors.
If explicitForward is false, the data will not override data forwarded with explicitForward == true.
Parameters
key The key of forwarded data
value The value of forwarded data
k The maximum distance to forward the distance. If there are more than k nodes between the forwarding nodes and another node b. b will not be able to fetch the data. Defaults to infinity.
Definition at line 563 of file node.h.
{
         forward_any(key, any_noncopyable(std::move(value)), k);
     }
Referenced by tpie::pipelining::bits::reverser_input_t< T >::end(), tpie::pipelining::bits::buffer_input_t< T >::end(), tpie::pipelining::bits::ami_input_t< dest_t >::propagate(), tpie::pipelining::bits::input_vector_t< dest_t, T, A >::propagate(), tpie::pipelining::bits::buffer_pull_output_t< T >::propagate(), tpie::pipelining::bits::range_t< dest_t >::propagate(), tpie::pipelining::bits::input_t< dest_t >::propagate(), tpie::pipelining::bits::sort_output_base< push_type< dest_t >::type, pred_t, store_t >::propagate(), tpie::pipelining::bits::ami_input_stack_t< dest_t >::propagate(), tpie::pipelining::serialization_bits::sort_output_base< Traits >::propagate(), tpie::pipelining::bits::pull_input_vector_t< T, A >::propagate(), tpie::pipelining::bits::internal_buffer_input_t< T >::propagate(), tpie::pipelining::bits::internal_reverser_input_t< T >::propagate(), tpie::pipelining::bits::ami_pull_input_stack_t< T >::propagate(), tpie::pipelining::bits::named_input_t< dest_t >::propagate(), tpie::pipelining::bits::reverser_output_t< dest_t >::propagate(), tpie::pipelining::bits::buffer_output_t< dest_t >::propagate(), tpie::pipelining::bits::pull_input_t< T >::propagate(), tpie::pipelining::bits::internal_reverser_output_t< dest_t >::propagate(), tpie::pipelining::bits::pull_reverse_input_t< T >::propagate(), tpie::pipelining::bits::zero_source_t< T >::propagate(), tpie::pipelining::bits::reverser_pull_output_t< T >::propagate(), tpie::pipelining::bits::named_pull_input_t< T >::propagate(), and tpie::pipelining::bits::internal_reverser_pull_output_t< T >::propagate().
forward_any()
void tpie::pipelining::node::forward_any (std::string key, any_noncopyable value, memory_size_type k = std::numeric_limits< memory_size_type >::max()) inherited
See node::forward.
Referenced by tpie::pipelining::bits::Forwarder< dest_t >::prepare().
get_available_memory()
memory_size_type tpie::pipelining::node::get_available_memory () const inline inherited
Get the amount of memory assigned to this node.
Definition at line 199 of file node.h.
{
         return get_available_of_resource(MEMORY);
     }
get_available_of_resource()
memory_size_type tpie::pipelining::node::get_available_of_resource (resource_type type) const inline inherited
Get the amount of the specific resource assigned to this node.
Definition at line 137 of file node.h.
{
         return m_parameters.resource_parameters[type].available;
     }
get_datastructure()
template<typename T > T& tpie::pipelining::node::get_datastructure (const std::string & name) inline inherited
Returns a previously declared datastructure.
Parameters
name the name of the datastructure
Template Parameters
the type of the datastructure
Definition at line 737 of file node.h.
{
         bits::node_map::datastructuremap_t & structures = get_node_map()->find_authority()->get_datastructures();
         bits::node_map::datastructuremap_t::iterator i = structures.find(name);
         if(i == structures.end())
             throw tpie::exception("attempted to get non-registered datastructure");
         return any_cast<T>(i->second.second);
     }
get_datastructure_memory()
memory_size_type tpie::pipelining::node::get_datastructure_memory (const std::string & name) inherited
Returns the memory assigned to a datastructure.
Parameters
name the name of the datastructure
get_id()
node_token::id_t tpie::pipelining::node::get_id () const inline inherited
Get the internal node ID of this node (mainly for debugging purposes).
Definition at line 258 of file node.h.
{
         return token.id();
     }
get_maximum_memory()
memory_size_type tpie::pipelining::node::get_maximum_memory () const inline inherited
Get the maximum amount of memory declared by this node.
Defaults to maxint when no maximum has been set.
Definition at line 185 of file node.h.
{
         return get_maximum_resource_usage(MEMORY);
     }
get_maximum_resource_usage()
memory_size_type tpie::pipelining::node::get_maximum_resource_usage (resource_type type) const inline inherited
Get the maximum amount of the resource declared by this node.
Defaults to maxint when no maximum has been set.
Definition at line 123 of file node.h.
{
         return m_parameters.resource_parameters[type].maximum;
     }
get_memory_fraction()
double tpie::pipelining::node::get_memory_fraction () const inline inherited
Get the memory priority of this node.
Definition at line 192 of file node.h.
{
         return get_resource_fraction(MEMORY);
     }
get_minimum_memory()
memory_size_type tpie::pipelining::node::get_minimum_memory () const inline inherited
Get the minimum amount of memory declared by this node.
Defaults to zero when no minimum has been set.
Definition at line 177 of file node.h.
{
         return get_minimum_resource_usage(MEMORY);
     }
get_minimum_resource_usage()
memory_size_type tpie::pipelining::node::get_minimum_resource_usage (resource_type type) const inline inherited
Get the minimum amount of the resource declared by this node.
Defaults to zero when no minimum has been set.
Definition at line 115 of file node.h.
{
         return m_parameters.resource_parameters[type].minimum;
     }
get_name()
const std::string& tpie::pipelining::node::get_name () inherited
Get this node's name.
For purposes of pipeline debugging and phase naming for progress indicator breadcrumbs.
get_name_priority()
priority_type tpie::pipelining::node::get_name_priority () inline inherited
Get the priority of this node's name.
For purposes of pipeline debugging and phase naming for progress indicator breadcrumbs.
Definition at line 348 of file node.h.
{
         return m_parameters.namePriority;
     }
get_node_map()
bits::node_map::ptr tpie::pipelining::node::get_node_map () const inline inherited
Get the local node map, mapping node IDs to node pointers for all the nodes reachable from this one.
Definition at line 250 of file node.h.
{
         return token.get_map();
     }
Referenced by tpie::pipelining::virtual_chunk< Input, Output >::operator=(), and tpie::pipelining::virtual_chunk_pull< Input, Output >::operator=().
get_phase_name()
const std::string& tpie::pipelining::node::get_phase_name () inherited
Get this node's phase name.
For purposes of pipeline debugging and phase naming for progress indicator breadcrumbs.
get_phase_name_priority()
priority_type tpie::pipelining::node::get_phase_name_priority () inline inherited
Get the priority of this node's pdane name.
For purposes of pipeline debugging and phase naming for progress indicator breadcrumbs.
Definition at line 368 of file node.h.
{
         return m_parameters.phaseNamePriority;
     }
get_plot_options()
flags<PLOT> tpie::pipelining::node::get_plot_options () const inline inherited
Get options specified for plot(), as a combination of node::PLOT values.
Definition at line 450 of file node.h.
{
         return m_plotOptions;
     }
get_progress_indicator()
progress_indicator_base* tpie::pipelining::node::get_progress_indicator () inline inherited
Used internally. Get the progress indicator used.
Definition at line 414 of file node.h.
{
         return m_pi;
     }
get_resource_being_assigned()
resource_type tpie::pipelining::node::get_resource_being_assigned () const inline inherited
Used internally to check order of method calls.
Definition at line 435 of file node.h.
{
         return m_resourceBeingAssigned;
     }
get_resource_fraction()
double tpie::pipelining::node::get_resource_fraction (resource_type type) const inline inherited
Get the priority for the specific resource of this node.
Definition at line 130 of file node.h.
{
         return m_parameters.resource_parameters[type].fraction;
     }
get_state()
STATE tpie::pipelining::node::get_state () const inline inherited
Used internally to check order of method calls.
Definition at line 421 of file node.h.
{
         return m_state;
     }
get_steps()
stream_size_type tpie::pipelining::node::get_steps () inline inherited
Used internally for progress indication.
Get the number of times the node expects to call step() at most.
Definition at line 396 of file node.h.
{
         return m_parameters.stepsTotal;
     }
get_token()
const node_token& tpie::pipelining::node::get_token () const inline inherited
Get the node_token that maps this node's ID to a pointer to this.
Definition at line 631 of file node.h.
{
         return token;
     }
get_used_memory()
memory_size_type tpie::pipelining::node::get_used_memory () const inline inherited
Get the amount of memory currently used by this node.
Definition at line 239 of file node.h.
{
         memory_size_type ans=0;
         for (const auto & p: m_buckets)
             if (p) ans += p->count;
         return ans;
     }
go()
virtual void tpie::pipelining::node::go () inline virtual inherited
For initiator nodes, execute this phase by pushing all items to be pushed.
For non-initiator nodes, the default implementation throws a not_initiator_node exception.
Reimplemented in tpie::pipelining::bits::pull_source_t< dest_t, fact_t >, tpie::pipelining::serialization_bits::buffer_output_t< dest_t >, tpie::pipelining::bits::pull_output_t< source_t >, tpie::pipelining::bits::pull_output_iterator_t< dest_t, IT >, tpie::pipelining::bits::push_input_iterator_t< dest_t, IT >, tpie::pipelining::serialization_bits::reverser_output_t< dest_t >, tpie::pipelining::bits::sort_output_t< pred_t, dest_t, store_t >, tpie::pipelining::serialization_bits::sort_output_t< Traits, dest_t >, tpie::pipelining::bits::internal_reverser_output_t< dest_t >, tpie::pipelining::bits::sort_pull_output_t< T, pred_t, store_t >, tpie::pipelining::serialization_bits::sort_pull_output_t< Traits >, tpie::pipelining::bits::buffer_output_t< dest_t >, tpie::pipelining::bits::reverser_output_t< dest_t >, tpie::pipelining::bits::named_input_t< dest_t >, tpie::pipelining::bits::input_t< dest_t >, tpie::pipelining::bits::ami_input_stack_t< dest_t >, tpie::pipelining::bits::range_t< dest_t >, tpie::pipelining::serialization_bits::input_t< dest_t >, tpie::pipelining::bits::input_vector_t< dest_t, T, A >, tpie::pipelining::bits::ami_input_t< dest_t >, and tpie::pipelining::bits::scanf_ints_t< dest_t >.
Definition at line 308 of file node.h.
                       {
         log_warning() << "node subclass " << typeid(*this).name()
             << " is not an initiator node" << std::endl;
         throw not_initiator_node();
     }
References tpie::log_warning().
no_forward_through()
void tpie::pipelining::node::no_forward_through () inherited
Dissablow forwards through this node.
prepare()
virtual void tpie::pipelining::node::prepare () inline virtual inherited
Called before memory assignment but after depending phases have executed and ended.
The implementer may use fetch and forward in this phase. The implementer does not have to call the super prepare-method; its default implementation is empty.
Reimplemented in tpie::pipelining::bits::preparer_t< dest_t, F >, tpie::pipelining::join< T >::source_impl< dest_t >, tpie::pipelining::split< T >::source_impl< dest_t >, and tpie::pipelining::bits::Forwarder< dest_t >.
Definition at line 268 of file node.h.
{
     }
propagate()
virtual void tpie::pipelining::node::propagate () inline virtual inherited
Propagate stream metadata.
The implementation may fetch() and forward() metadata such as number of items or the size of a single item.
The pipelining framework calls propagate() on the nodes in the item flow graph in a topological order.
The default implementation does nothing.
Reimplemented in tpie::pipelining::bits::pull_source_t< dest_t, fact_t >, tpie::pipelining::serialization_bits::buffer_pull_output_t< T >, tpie::pipelining::serialization_bits::buffer_output_t< dest_t >, tpie::pipelining::bits::propagater_t< dest_t, F >, tpie::pipelining::serialization_bits::buffer_input_t< T >, tpie::pipelining::bits::internal_reverser_pull_output_t< T >, tpie::pipelining::serialization_bits::reverser_pull_output_t< T >, tpie::pipelining::bits::named_pull_input_t< T >, tpie::pipelining::bits::reverser_pull_output_t< T >, tpie::pipelining::serialization_bits::reverser_output_t< dest_t >, tpie::pipelining::bits::zero_source_t< T >, tpie::pipelining::bits::pull_reverse_input_t< T >, tpie::pipelining::bits::internal_reverser_output_t< dest_t >, tpie::pipelining::bits::pull_input_t< T >, tpie::pipelining::serialization_bits::reverser_input_t< T >, tpie::pipelining::bits::buffer_output_t< dest_t >, tpie::pipelining::bits::reverser_output_t< dest_t >, tpie::pipelining::bits::named_input_t< dest_t >, tpie::pipelining::bits::ami_pull_input_stack_t< T >, tpie::pipelining::bits::internal_reverser_input_t< T >, tpie::pipelining::bits::internal_buffer_input_t< T >, tpie::pipelining::bits::pull_input_vector_t< T, A >, tpie::pipelining::serialization_bits::sort_output_base< Traits >, tpie::pipelining::bits::ami_input_stack_t< dest_t >, tpie::pipelining::bits::input_t< dest_t >, tpie::pipelining::bits::sort_output_base< T, pred_t, store_t >, tpie::pipelining::bits::sort_output_base< push_type< dest_t >::type, pred_t, store_t >, tpie::pipelining::serialization_bits::input_t< dest_t >, tpie::pipelining::bits::buffer_pull_output_t< T >, tpie::pipelining::bits::internal_buffer_pull_output_t< T >, tpie::pipelining::bits::input_vector_t< dest_t, T, A >, tpie::pipelining::bits::ami_input_t< dest_t >, and tpie::pipelining::bits::range_t< dest_t >.
Definition at line 282 of file node.h.
{
     }
proxy_progress_indicator()
progress_indicator_base* tpie::pipelining::node::proxy_progress_indicator () inherited
Get a non-initialized progress indicator for use with external implementations.
When step() is called on a proxying progress indicator, step() is called on the node according to the number of steps declared in progress_indicator_base::init() and in node::set_steps().
pull()
item_type tpie::pipelining::node::pull () inline inherited
For pull nodes, pull the next item from this node.
push()
void tpie::pipelining::node::push (const item_type & item) inline inherited
For push nodes, push the next item to this node.
register_datastructure_usage()
void tpie::pipelining::node::register_datastructure_usage (const std::string & name, double priority = 1) inherited
Registers a datastructure.
Parameters
name the name of the datastructure
priority the priority that should be given to this datastructure when assigning memory
resource_available_changed()
virtual void tpie::pipelining::node::resource_available_changed (resource_type , memory_size_type) inline virtual inherited
Called by the resource manager to notify the node's available amount of resource has changed.
Reimplemented in tpie::pipelining::bits::sort_output_base< T, pred_t, store_t >, and tpie::pipelining::bits::sort_output_base< push_type< dest_t >::type, pred_t, store_t >.
Definition at line 165 of file node.h.
{
     }
set_available_memory()
virtual void tpie::pipelining::node::set_available_memory (memory_size_type availableMemory) inline virtual inherited
Called by the memory manager to set the amount of memory assigned to this node.
Reimplemented in tpie::pipelining::serialization_bits::sort_output_base< Traits >.
Definition at line 232 of file node.h.
{
         unused(availableMemory);
     }
References tpie::unused().
set_breadcrumb()
void tpie::pipelining::node::set_breadcrumb (const std::string & breadcrumb) inline inherited
Used internally when a pair_factory has a name set.
Definition at line 388 of file node.h.
{
         m_parameters.name = m_parameters.name.empty() ? breadcrumb : (breadcrumb + " | " + m_parameters.name);
     }
set_datastructure()
template<typename T > void tpie::pipelining::node::set_datastructure (const std::string & name, T datastructure) inline inherited
Returns a previously declared datastructure.
Parameters
name the name of the datastructure
datastructure the datastructure itself
Definition at line 721 of file node.h.
{
         bits::node_map::datastructuremap_t & structures = get_node_map()->find_authority()->get_datastructures();
         bits::node_map::datastructuremap_t::iterator i = structures.find(name);
         if(i == structures.end())
             throw tpie::exception("attempted to set non-registered datastructure");
         i->second.second = move_if_movable<T>(datastructure);
     }
set_datastructure_memory_limits()
void tpie::pipelining::node::set_datastructure_memory_limits (const std::string & name, memory_size_type min, memory_size_type max = std::numeric_limits< memory_size_type >::max()) inherited
Assign memory to a registered datastructure.
Parameters
name the name of the datastructure
min the minimum amount of memory required by the datastructure
max the maximum amount of memory used by the datastructure
set_maximum_memory()
void tpie::pipelining::node::set_maximum_memory (memory_size_type maximumMemory) inline inherited
Called by implementers to declare maximum memory requirements.
To signal that you don't want any memory, set minimum memory and the memory fraction to zero.
Definition at line 216 of file node.h.
{
         set_maximum_resource_usage(MEMORY, maximumMemory);
     }
Referenced by tpie::pipelining::bits::sort_output_base< push_type< dest_t >::type, pred_t, store_t >::propagate(), and tpie::pipelining::serialization_bits::sort_output_base< Traits >::propagate().
set_maximum_resource_usage()
void tpie::pipelining::node::set_maximum_resource_usage (resource_type type, memory_size_type usage) inherited
Called by implementers to declare maximum resource requirements.
To signal that you don't want to use this resource, set minimum resource usage and the resource fraction to zero.
set_memory_fraction()
void tpie::pipelining::node::set_memory_fraction (double f) inline inherited
Set the memory priority of this node.
Memory is distributed proportionally to the priorities of the nodes in the given phase.
Definition at line 224 of file node.h.
{
         set_resource_fraction(MEMORY, f);
     }
Referenced by tpie::pipelining::bits::sort_output_base< push_type< dest_t >::type, pred_t, store_t >::propagate(), and tpie::pipelining::serialization_bits::sort_output_base< Traits >::propagate().
set_minimum_memory()
void tpie::pipelining::node::set_minimum_memory (memory_size_type minimumMemory) inline inherited
Called by implementers to declare minimum memory requirements.
Definition at line 206 of file node.h.
{
         set_minimum_resource_usage(MEMORY, minimumMemory);
     }
Referenced by tpie::pipelining::bits::sort_output_base< push_type< dest_t >::type, pred_t, store_t >::propagate(), and tpie::pipelining::serialization_bits::sort_output_base< Traits >::propagate().
set_minimum_resource_usage()
void tpie::pipelining::node::set_minimum_resource_usage (resource_type type, memory_size_type usage) inherited
Called by implementers to declare minimum resource requirements.
set_name()
void tpie::pipelining::node::set_name (const std::string & name, priority_type priority = PRIORITY_USER) inherited
Set this node's name.
For purposes of pipeline debugging and phase naming for progress indicator breadcrumbs.
set_phase_name()
void tpie::pipelining::node::set_phase_name (const std::string & name, priority_type priority = PRIORITY_USER) inherited
Set this node's phase name.
For purposes of pipeline debugging and phase naming for progress indicator breadcrumbs.
set_plot_options()
void tpie::pipelining::node::set_plot_options (flags< PLOT > options) inline inherited
Set options specified for plot(), as a combination of node::PLOT values.
Definition at line 458 of file node.h.
{
         m_plotOptions = options;
     }
set_progress_indicator()
void tpie::pipelining::node::set_progress_indicator (progress_indicator_base * pi) inline inherited
Used internally. Set the progress indicator to use.
Definition at line 407 of file node.h.
{
         m_pi = pi;
     }
set_resource_being_assigned()
void tpie::pipelining::node::set_resource_being_assigned (resource_type type) inline inherited
Used internally to check order of method calls.
Definition at line 442 of file node.h.
{
         m_resourceBeingAssigned = type;
     }
set_resource_fraction()
void tpie::pipelining::node::set_resource_fraction (resource_type type, double f) inherited
Set the resource priority of this node.
Resources are distributed proportionally to the priorities of the nodes in the given phase.
set_state()
void tpie::pipelining::node::set_state (STATE s) inline inherited
Used internally to check order of method calls.
Definition at line 428 of file node.h.
{
         m_state = s;
     }
set_steps()
void tpie::pipelining::node::set_steps (stream_size_type steps) inherited
Called by implementers that intend to call step().
Parameters
steps The number of times step() is called at most.
Referenced by tpie::pipelining::bits::ami_input_t< dest_t >::propagate(), tpie::pipelining::bits::input_vector_t< dest_t, T, A >::propagate(), tpie::pipelining::bits::buffer_pull_output_t< T >::propagate(), tpie::pipelining::serialization_bits::input_t< dest_t >::propagate(), tpie::pipelining::bits::range_t< dest_t >::propagate(), tpie::pipelining::bits::sort_output_base< push_type< dest_t >::type, pred_t, store_t >::propagate(), tpie::pipelining::bits::input_t< dest_t >::propagate(), tpie::pipelining::bits::ami_input_stack_t< dest_t >::propagate(), tpie::pipelining::serialization_bits::sort_output_base< Traits >::propagate(), tpie::pipelining::bits::ami_pull_input_stack_t< T >::propagate(), tpie::pipelining::bits::named_input_t< dest_t >::propagate(), tpie::pipelining::bits::reverser_output_t< dest_t >::propagate(), tpie::pipelining::bits::buffer_output_t< dest_t >::propagate(), tpie::pipelining::bits::pull_input_t< T >::propagate(), tpie::pipelining::bits::internal_reverser_output_t< dest_t >::propagate(), tpie::pipelining::bits::pull_reverse_input_t< T >::propagate(), tpie::pipelining::serialization_bits::reverser_output_t< dest_t >::propagate(), tpie::pipelining::bits::named_pull_input_t< T >::propagate(), tpie::pipelining::serialization_bits::reverser_pull_output_t< T >::propagate(), tpie::pipelining::serialization_bits::buffer_output_t< dest_t >::propagate(), tpie::pipelining::serialization_bits::buffer_pull_output_t< T >::propagate(), and tpie::pipelining::bits::pull_source_t< dest_t, fact_t >::propagate().
step()
void tpie::pipelining::node::step (stream_size_type steps = 1) inline inherited
Step the progress indicator.
Parameters
steps How many steps to step.
Definition at line 653 of file node.h.
{
         assert(get_state() == STATE_IN_END ||
                get_state() == STATE_IN_BEGIN ||
                get_state() == STATE_AFTER_BEGIN ||
                get_state() == STATE_IN_END ||
                get_state() == STATE_IN_GO);
         if (m_stepsLeft < steps)
             step_overflow();
         else
             m_stepsLeft -= steps;
         m_pi->step(steps);
     }
Referenced by tpie::pipelining::bits::ami_input_t< dest_t >::go(), tpie::pipelining::bits::input_vector_t< dest_t, T, A >::go(), tpie::pipelining::serialization_bits::input_t< dest_t >::go(), tpie::pipelining::bits::range_t< dest_t >::go(), tpie::pipelining::bits::ami_input_stack_t< dest_t >::go(), tpie::pipelining::bits::input_t< dest_t >::go(), tpie::pipelining::bits::named_input_t< dest_t >::go(), tpie::pipelining::bits::reverser_output_t< dest_t >::go(), tpie::pipelining::bits::buffer_output_t< dest_t >::go(), tpie::pipelining::bits::internal_reverser_output_t< dest_t >::go(), tpie::pipelining::serialization_bits::sort_output_t< Traits, dest_t >::go(), tpie::pipelining::bits::sort_output_t< pred_t, dest_t, store_t >::go(), tpie::pipelining::serialization_bits::reverser_output_t< dest_t >::go(), tpie::pipelining::serialization_bits::buffer_output_t< dest_t >::go(), and tpie::pipelining::bits::pull_source_t< dest_t, fact_t >::go().
The documentation for this class was generated from the following file:
pipelining/file_stream.h