tpie::array_view_base< T > Class Template Reference
tpie::array_view_base< T > Class Template Reference
Base class for array_view.
#include <tpie/array_view_base.h>
Inherited by tpie::array_view< T >.
Classes
class iterator
Public Types
typedef T value_type
Type of values contained in the array.
Public Member Functions
array_view_base (T *start, T *end)
Pointer constructor.
iterator find (size_t idx) const throw ()
Return an iterator to the i'th element of the array.
T & at (size_t i) const throw ()
Return the element located at the given index.
bool empty () const
Check if the array is empty.
size_t size () const
Get number of elements in the array.
T & operator[] (size_t i) const
Return a reference to an array entry.
bool operator== (const array_view_base &other) const
Check if the other array has the same elements in the same order as this.
bool operator!= (const array_view_base &other) const
Check if the two arrays differ.
iterator begin () const
Return an iterator to the beginning of the array.
iterator end () const
Return an iterator to the end of the array.
T & front () const
Return the first element in the array.
T & back () const
Return the last element in the array.
Detailed Description
template<typename T>
class tpie::array_view_base< T >
Base class for array_view.
This is needed so that a tpie::array can be constructed from an array_view_base and an array_view can be constructed from a tpie::array.
Definition at line 40 of file array_view_base.h.
Member Typedef Documentation
value_type
template<typename T > typedef T tpie::array_view_base< T >::value_type
Type of values contained in the array.
Definition at line 74 of file array_view_base.h.
Constructor & Destructor Documentation
array_view_base()
template<typename T > tpie::array_view_base< T >::array_view_base (T * start, T * end) inline
Pointer constructor.
The structure will produce the elements in the memory range [start, end).
Parameters
start Pointer to first element of the array_view.
end Pointer past the last element of the array_view.
Definition at line 69 of file array_view_base.h.
 : m_start(start), m_end(end) {}
Member Function Documentation
at()
template<typename T > T& tpie::array_view_base< T >::at (size_t i) const throw () inline
Return the element located at the given index.
Parameters
i The index of the element returned.
Definition at line 92 of file array_view_base.h.
{
         assert(i < size());
         return *find(i);
     }
Referenced by tpie::array_view_base< const T >::operator!=(), tpie::array_view_base< const T >::operator==(), and tpie::array_view_base< const T >::operator[]().
back()
template<typename T > T& tpie::array_view_base< T >::back () const inline
Return the last element in the array.
Definition at line 168 of file array_view_base.h.
 {return *(m_end-1);}
begin()
template<typename T > iterator tpie::array_view_base< T >::begin () const inline
Return an iterator to the beginning of the array.
Returns
An iterator to the beginning of the array.
Definition at line 151 of file array_view_base.h.
 {return iterator(m_start);}
empty()
template<typename T > bool tpie::array_view_base< T >::empty () const inline
Check if the array is empty.
Returns
True if and only if size is 0.
Definition at line 102 of file array_view_base.h.
 {return m_end == m_start;}
end()
template<typename T > iterator tpie::array_view_base< T >::end () const inline
Return an iterator to the end of the array.
Returns
An iterator to the end of the array.
Definition at line 158 of file array_view_base.h.
 {return iterator(m_end);}
find()
template<typename T > iterator tpie::array_view_base< T >::find (size_t idx) const throw () inline
Return an iterator to the i'th element of the array.
Parameters
idx The index of the element we want an iterator to.
Returns
An iterator to the i'th element.
Definition at line 82 of file array_view_base.h.
{
         assert(idx <= size());
         return iterator(m_start + idx);
     }
Referenced by tpie::array_view_base< const T >::at().
front()
template<typename T > T& tpie::array_view_base< T >::front () const inline
Return the first element in the array.
Definition at line 163 of file array_view_base.h.
 {return *m_start;}
operator!=()
template<typename T > bool tpie::array_view_base< T >::operator!= (const array_view_base< T > & other) const inline
Check if the two arrays differ.
Parameters
other The array to compare against.
Returns
false If they are equal otherwise true.
Definition at line 140 of file array_view_base.h.
{
         if (size() != other.size()) return true;
         for (size_t i=0; i< size(); ++i) if (at(i) != other.at(i)) return true;
         return false;
     }
operator==()
template<typename T > bool tpie::array_view_base< T >::operator== (const array_view_base< T > & other) const inline
Check if the other array has the same elements in the same order as this.
Parameters
other The array to compare against.
Returns
True if they are equal, otherwise false.
Definition at line 128 of file array_view_base.h.
{
         if (size() != other.size()) return false;
         for (size_t i=0; i < size(); ++i) if (at(i) != other.at(i)) return false;
         return true;
     }
operator[]()
template<typename T > T& tpie::array_view_base< T >::operator[] (size_t i) const inline
Return a reference to an array entry.
Parameters
i The index of the entry to return.
Returns
Reference to the entry.
Definition at line 116 of file array_view_base.h.
{
         assert(i < size());
         return at(i);
     }
size()
template<typename T > size_t tpie::array_view_base< T >::size () const inline
Get number of elements in the array.
Returns
Number of elements in the array.
Definition at line 108 of file array_view_base.h.
 {return m_end - m_start;}
Referenced by tpie::array_view_base< const T >::at(), tpie::pipelining::parallel_bits::consumer_impl< Input, Output, dest_t >::consume(), tpie::array_view_base< const T >::find(), tpie::array_view_base< const T >::operator!=(), tpie::array_view_base< const T >::operator==(), tpie::array_view_base< const T >::operator[](), and tpie::pipelining::parallel_bits::before_impl< dest_t >::push_all().
The documentation for this class was generated from the following file:
array_view_base.h