tpie::pipelining::virtual_chunk< Input, Output > Class Template Reference
tpie::pipelining::virtual_chunk< Input, Output > Class Template Reference
Virtual chunk that has input and output.
#include <tpie/pipelining/virtual.h>
Public Member Functions
virtual_chunk ()
Constructor that leaves the virtual chunk unassigned.
template<typename fact_t >
virtual_chunk (pipe_middle< fact_t > &&pipe, virtual_container *ctr=nullptr)
Constructor that recursively constructs a node and takes ownership of it.
virtual_chunk (const virtual_chunk_end< Input > &left, const virtual_chunk_begin< Output > &right)
Construct a virtual chunk from an end and a begin chunk.
template<typename fact_t >
virtual_chunk & operator= (pipe_middle< fact_t > &&pipe)
Construct a node and assign it to this virtual chunk.
template<typename NextOutput >
virtual_chunk< Input, NextOutput > operator| (virtual_chunk< Output, NextOutput > dest)
Connect this virtual chunk to another chunk.
virtual_chunk_end< Input > operator| (virtual_chunk_end< Output > dest)
Connect this virtual chunk to another chunk.
operator bool () const noexcept
Test if it is not an empty chunk.
Friends
class bits::access
Detailed Description
template<typename Input, typename Output = Input>
class tpie::pipelining::virtual_chunk< Input, Output >
Virtual chunk that has input and output.
Definition at line 52 of file virtual.h.
Constructor & Destructor Documentation
virtual_chunk() [1/3]
template<typename Input , typename Output = Input> tpie::pipelining::virtual_chunk< Input, Output >::virtual_chunk () inline
Constructor that leaves the virtual chunk unassigned.
Definition at line 517 of file virtual.h.
         : m_input(nullptr)
         , m_output(nullptr)
     {}
virtual_chunk() [2/3]
template<typename Input , typename Output = Input> template<typename fact_t > tpie::pipelining::virtual_chunk< Input, Output >::virtual_chunk (pipe_middle< fact_t > && pipe, virtual_container * ctr = nullptr) inline
Constructor that recursively constructs a node and takes ownership of it.
Definition at line 527 of file virtual.h.
{
         *this = std::forward<pipe_middle<fact_t>>(pipe);
         set_container(ctr);
     }
virtual_chunk() [3/3]
template<typename Input , typename Output = Input> tpie::pipelining::virtual_chunk< Input, Output >::virtual_chunk (const virtual_chunk_end< Input > & left, const virtual_chunk_begin< Output > & right) inline
Construct a virtual chunk from an end and a begin chunk.
Items pushed into the virtual chunk are pushed into the left end chunk Items push out of the right begin chenk are pushed out of the virtual chunk
Definition at line 539 of file virtual.h.
         : virtual_chunk_base(left.get_node_map(), bits::virt_node::combine(left.get_node(), right.get_node()))
     {
         m_input = acc::get_input(left);
         m_output = acc::get_output(right);
     }
Member Function Documentation
operator bool()
template<typename Input , typename Output = Input> tpie::pipelining::virtual_chunk< Input, Output >::operator bool () const inline explicit noexcept
Test if it is not an empty chunk.
Definition at line 601 of file virtual.h.
{
         return m_input != nullptr;
     }
operator=()
template<typename Input , typename Output = Input> template<typename fact_t > virtual_chunk& tpie::pipelining::virtual_chunk< Input, Output >::operator= (pipe_middle< fact_t > && pipe) inline
Construct a node and assign it to this virtual chunk.
Definition at line 552 of file virtual.h.
{
         if (this->m_node) {
             log_error() << "Virtual chunk assigned twice" << std::endl;
             throw tpie::exception("Virtual chunk assigned twice");
         }
         typedef typename fact_t::template constructed_type<output_type> constructed_type;
         output_type temp(m_output);
         this->m_nodeMap = temp.get_node_map();
         fact_t f = std::move(pipe.factory);
         f.set_destination_kind_push();
         m_input = new bits::virtsrc_impl<constructed_type, Input>(f.construct(std::move(temp)));
         this->m_node = bits::virt_node::take_own(m_input);
         return *this;
     }
References tpie::pipelining::node::get_node_map(), tpie::log_error(), and tpie::pipelining::bits::virt_node::take_own().
operator|() [1/2]
template<typename Input , typename Output = Input> template<typename NextOutput > virtual_chunk<Input, NextOutput> tpie::pipelining::virtual_chunk< Input, Output >::operator| (virtual_chunk< Output, NextOutput > dest) inline
Connect this virtual chunk to another chunk.
Definition at line 572 of file virtual.h.
{
         if (empty()) {
             return *bits::assert_types_equal_and_return<Input, Output, virtual_chunk<Input, NextOutput> *>
                 ::go(&dest);
         }
         bits::virtsrc<Output> * dst=acc::get_input(dest);
         if (dest.empty() || !dst) {
             return *bits::assert_types_equal_and_return<Output, NextOutput, virtual_chunk<Input, NextOutput> *>
                 ::go(this);
         }
         m_output->set_destination(dst);
         return acc::construct<virtual_chunk<Input, NextOutput>>(*this, dest);
     }
operator|() [2/2]
template<typename Input , typename Output = Input> virtual_chunk_end<Input> tpie::pipelining::virtual_chunk< Input, Output >::operator| (virtual_chunk_end< Output > dest) inline
Connect this virtual chunk to another chunk.
Definition at line 589 of file virtual.h.
{
         if (empty()) {
             return *bits::assert_types_equal_and_return<Input, Output, virtual_chunk_end<Input> *>
                 ::go(&dest);
         }
         m_output->set_destination(acc::get_input(dest));
         return acc::construct<virtual_chunk_end<Input>>(*this, dest);
     }
The documentation for this class was generated from the following file:
pipelining/virtual.h