tpie::stack< T > Class Template Reference
tpie::stack< T > Class Template Reference
An implementation of an external-memory stack.
#include <tpie/stack.h>
Public Member Functions
stack (double blockFactor=1.0)
Initialize anonymous stack.
stack (const std::string &path, double blockFactor=1.0)
Initialize named, nontemporary stack.
stack (temp_file &tempFile, double blockFactor=1.0)
Initialize temporary stack.
~stack ()
Closes the underlying stream and truncates it to the logical end of the stack.
void push (const T &t)
Pushes one item onto the stack.
const T & pop ()
Pops one item from the stack.
const T & top ()
Peeks at the topmost item on the stack.
stream_size_type size () const
Returns the number of items currently on the stack.
bool empty () const
Returns whether the stack is empty or not.
Static Public Member Functions
static memory_size_type memory_usage (float blockFactor=1.0)
Compute the memory used by a stack.
Protected Attributes
file_stream< T > m_stream
The stream used to store the items.
Detailed Description
template<typename T>
class tpie::stack< T >
An implementation of an external-memory stack.
Definition at line 40 of file stack.h.
Constructor & Destructor Documentation
stack() [1/3]
template<typename T > tpie::stack< T >::stack (double blockFactor = 1.0) inline
Initialize anonymous stack.
Definition at line 46 of file stack.h.
         : m_stream(blockFactor)
         , m_buffer(buffer_size(blockFactor))
         , m_bufferItems(0)
     {
         m_stream.open(static_cast<memory_size_type>(0), access_normal,
                       compression_normal);
     }
stack() [2/3]
template<typename T > tpie::stack< T >::stack (const std::string & path, double blockFactor = 1.0) inline
Initialize named, nontemporary stack.
Parameters
path The path to a file used for storing the items.
blockFactor The block factor to use
Definition at line 61 of file stack.h.
         : m_stream(blockFactor)
         , m_buffer(buffer_size(blockFactor))
         , m_bufferItems(0)
     {
         m_stream.open(path, access_read_write,
                       static_cast<memory_size_type>(0), access_normal,
                       compression_normal);
         m_stream.seek(0, file_stream_base::end);
     }
stack() [3/3]
template<typename T > tpie::stack< T >::stack (temp_file & tempFile, double blockFactor = 1.0) inline
Initialize temporary stack.
Parameters
tempFile The temporary file containing the stack
blockFactor The block factor to use
Definition at line 78 of file stack.h.
         : m_stream(blockFactor)
         , m_buffer(buffer_size(blockFactor))
         , m_bufferItems(0)
     {
         m_stream.open(tempFile, access_read_write,
                       static_cast<memory_size_type>(0), access_normal,
                       compression_normal);
         m_stream.seek(0, file_stream_base::end);
     }
~stack()
template<typename T > tpie::stack< T >::~stack () inline
Closes the underlying stream and truncates it to the logical end of the stack.
Definition at line 94 of file stack.h.
              {
         empty_buffer();
         m_stream.truncate(m_stream.get_position());
     }
Member Function Documentation
empty()
template<typename T > bool tpie::stack< T >::empty () const inline
Returns whether the stack is empty or not.
m_file_stream.can_read_back();
Definition at line 139 of file stack.h.
{
         return size()  == 0;
     }
Referenced by tpie::pipelining::bits::reverser_pull_output_t< T >::can_pull(), and tpie::pipelining::bits::reverser_output_t< dest_t >::go().
memory_usage()
template<typename T > static memory_size_type tpie::stack< T >::memory_usage (float blockFactor = 1.0) inline static
Compute the memory used by a stack.
Definition at line 146 of file stack.h.
{
         return sizeof(stack<T>)
             + file_stream<T>::memory_usage(blockFactor)
             + array<T>::memory_usage(buffer_size(blockFactor));
     }
Referenced by tpie::ami::stack< item_type >::main_memory_usage().
pop()
template<typename T > const T& tpie::stack< T >::pop () inline
Pops one item from the stack.
Definition at line 113 of file stack.h.
{
         if (m_bufferItems) return m_buffer[--m_bufferItems];
         const T & item = m_stream.read_back();
         return item;
     }
Referenced by tpie::pipelining::bits::ami_input_stack_t< dest_t >::go(), tpie::pipelining::bits::reverser_output_t< dest_t >::go(), and tpie::pipelining::bits::reverser_pull_output_t< T >::pull().
push()
template<typename T > void tpie::stack< T >::push (const T & t) inline
Pushes one item onto the stack.
Returns ERROR_* as given by the underlying stream.
Parameters
t The item to push onto the stack.
Definition at line 105 of file stack.h.
{
         if (m_buffer.size() == m_bufferItems) empty_buffer();
         m_buffer[m_bufferItems++] = t;
     }
size()
template<typename T > stream_size_type tpie::stack< T >::size () const inline
Returns the number of items currently on the stack.
Definition at line 132 of file stack.h.
{
         return m_stream.offset()+m_bufferItems;
     }
Referenced by tpie::stack< item_type >::empty(), tpie::pipelining::bits::ami_input_stack_t< dest_t >::propagate(), and tpie::pipelining::bits::ami_pull_input_stack_t< T >::propagate().
top()
template<typename T > const T& tpie::stack< T >::top () inline
Peeks at the topmost item on the stack.
Definition at line 122 of file stack.h.
{
         if (m_bufferItems) return m_buffer[m_bufferItems-1];
         m_buffer[0] = m_stream.read_back();
         m_stream.read();
         return m_buffer[0];
     }
Member Data Documentation
m_stream
template<typename T > file_stream<T> tpie::stack< T >::m_stream protected
The stream used to store the items.
Definition at line 155 of file stack.h.
Referenced by tpie::stack< item_type >::pop(), tpie::stack< item_type >::size(), tpie::stack< item_type >::stack(), tpie::stack< item_type >::top(), and tpie::stack< item_type >::~stack().
The documentation for this class was generated from the following file:
stack.h