var dir_83a1566a4913ee062866be636c020e08 =
[
    [ "parallel", "dir_3f85e168dce96470192c2bf4e15ca6c1.html", "dir_3f85e168dce96470192c2bf4e15ca6c1" ],
    [ "ami_glue.h", "ami__glue_8h_source.html", null ],
    [ "buffer.h", "pipelining_2buffer_8h.html", "pipelining_2buffer_8h" ],
    [ "chunker.h", "chunker_8h_source.html", null ],
    [ "container.h", "container_8h_source.html", null ],
    [ "exception.h", "pipelining_2exception_8h_source.html", null ],
    [ "factory_base.h", "factory__base_8h_source.html", null ],
    [ "factory_helpers.h", "factory__helpers_8h_source.html", null ],
    [ "file_stream.h", "pipelining_2file__stream_8h_source.html", null ],
    [ "filter.h", "filter_8h_source.html", null ],
    [ "forwarder.h", "forwarder_8h_source.html", null ],
    [ "helpers.h", "helpers_8h_source.html", null ],
    [ "internal_buffer.h", "internal__buffer_8h.html", [
      [ "internal_buffer_pull_output_t", "classtpie_1_1pipelining_1_1bits_1_1internal__buffer__pull__output__t.html", "classtpie_1_1pipelining_1_1bits_1_1internal__buffer__pull__output__t" ],
      [ "internal_buffer_input_t", "classtpie_1_1pipelining_1_1bits_1_1internal__buffer__input__t.html", "classtpie_1_1pipelining_1_1bits_1_1internal__buffer__input__t" ],
      [ "internal_passive_buffer", "classtpie_1_1pipelining_1_1internal__passive__buffer.html", "classtpie_1_1pipelining_1_1internal__passive__buffer" ]
    ] ],
    [ "join.h", "join_8h_source.html", null ],
    [ "maintain_order_type.h", "maintain__order__type_8h.html", "maintain__order__type_8h" ],
    [ "map.h", "map_8h_source.html", null ],
    [ "merge.h", "merge_8h_source.html", null ],
    [ "merge_sorter.h", "merge__sorter_8h_source.html", null ],
    [ "merger.h", "merger_8h_source.html", null ],
    [ "node.h", "pipelining_2node_8h_source.html", null ],
    [ "node_map_dump.h", "node__map__dump_8h_source.html", null ],
    [ "node_name.h", "node__name_8h_source.html", null ],
    [ "node_set.h", "node__set_8h_source.html", null ],
    [ "node_traits.h", "node__traits_8h_source.html", null ],
    [ "numeric.h", "numeric_8h_source.html", null ],
    [ "ordered_merge.h", "ordered__merge_8h_source.html", null ],
    [ "pair_factory.h", "pair__factory_8h_source.html", null ],
    [ "parallel.h", "parallel_8h.html", null ],
    [ "pipe_base.h", "pipe__base_8h_source.html", null ],
    [ "pipeline.h", "pipeline_8h_source.html", null ],
    [ "predeclare.h", "pipelining_2predeclare_8h.html", null ],
    [ "priority_type.h", "priority__type_8h_source.html", null ],
    [ "reverse.h", "reverse_8h_source.html", null ],
    [ "runtime.h", "runtime_8h_source.html", null ],
    [ "serialization.h", "serialization_8h.html", "serialization_8h" ],
    [ "serialization_sort.h", "serialization__sort_8h_source.html", null ],
    [ "sort.h", "pipelining_2sort_8h_source.html", null ],
    [ "sort_parameters.h", "sort__parameters_8h_source.html", null ],
    [ "split.h", "split_8h_source.html", null ],
    [ "std_glue.h", "std__glue_8h_source.html", null ],
    [ "stdio.h", "pipelining_2stdio_8h_source.html", null ],
    [ "store.h", "store_8h_source.html", null ],
    [ "subpipeline.h", "subpipeline_8h_source.html", null ],
    [ "tokens.h", "tokens_8h.html", "tokens_8h" ],
    [ "uniq.h", "uniq_8h_source.html", null ],
    [ "virtual.h", "virtual_8h.html", "virtual_8h" ],
    [ "visit.h", "visit_8h_source.html", null ]
];